### ISSUE TITLE
 "extendable preferred share" is not a recognized financial term

### ISSUE THREAD

**Issue by rivettp** [edmcouncil/fibo#1137]
I could not google anything for "extendable preferred share": I literally got zero results! Is it really a thing?

_Originally posted by @rivettp in https://github.com/edmcouncil/fibo/pull/1130#discussion_r480406709_

**Comment by ElisaKendall** [comment]
Issue SEC-73 is about the representation of the CFI standard in FIBO.  Under preferred shares, in section 6.2.3, under the second attribute (Redemption), you'll find that Extendible is one of the features tracked in the CFI standard.  It applies only to redeemable preferred shares, and since redeemable preferred shares are already a specialized kind of thing, it may be difficult to find any information in a generic search.  We have discussed this in our calls, and our SMEs have agreed that we need to represent this.

Not sure how extensive your search was, but here is a Bloomberg article that was published today that talks about extending the redemption date on preferred shares - https://www.bloomberg.com/press-releases/2019-04-02/neuberger-berman-closed-end-municipal-funds-announce-extension-of-preferred-shares-term-and-partial-redemption.

I recommend that we close this issue with no change.

**Comment by rivettp** [comment]
In the CFI definitions https://sec.report/CFI/EPNEDB I believe it's spelled extendible with an i rather than extendable with an a. So I'd be OK if we had extendible in the synonym.
