### ISSUE TITLE
New hygiene test - cycles in class hierarchy

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1190]
https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t3-including-cycles-in-the-hierarchy mentions a test to find cycles in class hierarchy.

I think that the following test should work:
```
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

##
# banner Class hierarchy shouldn't be circular.

SELECT DISTINCT ?error ?class
WHERE {
  FILTER (CONTAINS(str(?class), "edmcouncil"))
  ?class rdfs:subClassOf+ ?class

  BIND (
    concat ("PRODERROR: There is a hierarchy cycle around ", str(?class)) AS ?error
    )
}
```

Note that this test takes class hierarchy cycles seriously and does not allow them in PROD.

**Comment by ElisaKendall** [comment]
This will be really useful - hopefully we won't find any :).  I'm certain that there are some in DEV though.

**Comment by rivettp** [comment]
@mereolog since rdfs:subClassOf is transitive it's redundant to have the "+" in the path.
However a class is also a subclass of itself so this test will give a warning about everything!
I think you'd have to use sesame:directSubClassOf+.
Unless you somehow specify that the query is to be run without reasoning.

**Comment by rivettp** [comment]
We should have a similar test for subPropertyOf cycles.

**Comment by mereolog** [comment]
As for:
> @mereolog since rdfs:subClassOf is transitive it's redundant to have the "+" in the path.
> However a class is also a subclass of itself so this test will give a warning about everything!
> I think you'd have to use sesame:directSubClassOf+.
> Unless you somehow specify that the query is to be run without reasoning.

Your statements are both logically and factually false.

As for the latter try to run this query over the whole FIBO (Dev or Prod) or any single FIBO ontology (as of today), it will return no triple, i.e., the result set will be empty. This, by the way, means that there are no cycles in FIBO class hierarchy (as of today). So this test does not give a warning about everything, contrary to what you said.

As for the former, the semantics of rdfs:subClassOf makes it a reflexive transitive relation, but most of (all?) SPARQL engines do not know about this semantics, i.e., they do not do reasoning and you cannot even specify that queries are run with or without reasoning. So if your RDF graph is not explicitly transitively closed (and most of them are not, for a good reason), querying with 'rdfs:subClassOf' will produce different results then querying with 'rdfs:subClassOf+'.
For example, if you run the following two queries over https://spec.edmcouncil.org/fibo/ontology/FND/AgentsAndPeople/People/, you will get different results:
```
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:   <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?class
WHERE {
  ?class rdfs:subClassOf <https://spec.edmcouncil.org/fibo/ontology/FND/AgentsAndPeople/People/Person>.
}
```

```
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:   <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?class
WHERE {
  ?class rdfs:subClassOf+ <https://spec.edmcouncil.org/fibo/ontology/FND/AgentsAndPeople/People/Person>.
}
```

A similar remark applies to your comment about reflexivity. 
For instance, because https://spec.edmcouncil.org/fibo/ontology/FND/AgentsAndPeople/People does not explicitly contain a triple 
fibo-fnd-aap-ppl:Person rdfs:subClassOf fibo-fnd-aap-ppl:Person, therefore the following query returns no result (as of today's version of FIBO):
```
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:   <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?class
WHERE {
   <https://spec.edmcouncil.org/fibo/ontology/FND/AgentsAndPeople/People/Person> rdfs:subClassOf <https://spec.edmcouncil.org/fibo/ontology/FND/AgentsAndPeople/People/Person>.
}
```

**Comment by rivettp** [comment]
Well here's a quote from the OWL 2 Primer https://www.w3.org/TR/owl2-primer/ section 4.2:
"Technically, this means that the subclass relationship between classes is transitive. Besides this, it is also reflexive, meaning that every class is its own subclass – this is intuitive as well since clearly, every person is a person etc."
So my statement is hardly **logically** false.

With respect to factually false, my last sentence said "Unless you somehow specify that the query is to be run without reasoning." which it seems is what you have done, albeit implicitly since it seems to be the default in your environment.
I did run your query in Stardog Studio with reasoning enabled and it did return a list of all classes. 

It prompts the question as to whether we should assume inferencing or not for hygiene and other quality tests. I don't think it's something we've explicitly specified up to now, but it would be needed for tests such as conveniently checking that each property has an inverse (not that I think that's a good idea) as per your proposed query which relies on inferring **a inverseOf b** from **b inverseOf a**.

**Comment by mereolog** [comment]
SPARQL is a query language for RDF so the RDFS or OWL semantics is irrelevant for SPARQL queries.
https://www.w3.org/TR/sparql11-query/#sparqlDefinition makes this sufficiently clear, in particular no definition there guarantees the transitivity or reflexivity of rdfs:subClassOf in SPARQL queries. That is to say, the evaluation conditions specified in https://www.w3.org/TR/sparql11-query/#sparqlAlgebraEval imply that a query like:
```
SELECT DISTINCT ?class
WHERE {
   <https://spec.edmcouncil.org/fibo/ontology/FND/AgentsAndPeople/People/Person> rdfs:subClassOf <https://spec.edmcouncil.org/fibo/ontology/FND/AgentsAndPeople/People/Person>.
} 
```
should return the empty multiset of solution mappings when run against the RDF graph given by https://spec.edmcouncil.org/fibo/ontology/FND/AgentsAndPeople/People/.
The result you get in Stardog Studio does not come from a "pure" SPARQL query because the SPARQL syntax does not have any clause that would allow you enable or disable reasoning (besides, of course, the property paths infrastructure, which can be used as a substitute thereof).

And, as far as I know, our current DevOps process runs SPARQL queries in Java ARQ, which is a pure SPARQL query engine without any reasoning mechanism. 
@przemekgradzki is there a plugin to ARQ that supports reasoning?
