### ISSUE TITLE
New hygiene test - missing inverse properties

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1192]
https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t10-missing-inverse-relationships suggests that, as a rule of thumb, all object properties should have inverse properties.

The following query should find all that don't:
```
prefix owl:   <http://www.w3.org/2002/07/owl#> 

##
# banner Object properties should have inverse properties.

SELECT ?warning ?p
WHERE
{
?p rdf:type owl:ObjectProperty .
FILTER (CONTAINS(str(?p), "edmcouncil"))
FILTER NOT EXISTS {?p owl:inverseOf ?i}
BIND (concat ("WARN: object property ", str(?p), " has no inverse.") AS ?warning)
} 
```

See also: https://github.com/edmcouncil/ontology-publisher/issues/20.

**Comment by ElisaKendall** [comment]
As I mentioned on the last issue, it would be great to separate these warnings into a separate file - it may be some time before we work through most of these, and I think there will be a lot of them.

**Comment by rivettp** [comment]
I don't think this should be a hygiene test. Even when we discussed it https://wiki.edmcouncil.org/pages/viewpage.action?pageId=9012140 we barely reached a consensus, which was largely a factor of who happened to be on a call since the previous occasion reached a different conclusion. Even the item T10 in the ontology guide says "inverses are **often** appropriate and **should** be included in the ontology where the "other half"/source relationship is defined." which is hardly definitive. And there is also the cognitive load (FIBO is large enough as it is), the maintenance load, and where to put definitions https://wiki.edmcouncil.org/display/FLT/Definitions+for+Inverse+Properties . 

Since this was last debated exactly 2 years ago now, I've personally modeled and reused many ontologies, as well as continuing to maintain and extend FIBO. I shudder at the thought of maintaining an inverse for each property.
This all IMO comes from a data modeling mindset as opposed to a logic/ontology mindset. Even UML does not require inverses!

As well as my own experience I'd like to appeal the case based on new _evidence_: AFAIR one aspect not discussed back then is the impact on dependencies - it almost forces circular dependencies if the domain/range are in different ontologies: unless you take the awkward approach (not supported by all tools) of maintaining the X inverseOf Y triple in the same ontology as Y.

Another factor not mentioned then is that use of inverses requires inferencing. Which is not supported by many mainstream platforms (e.g. AWS Neptune). People will be tempted to use the inverse property in queries and suffer deployment issues or an unexpected and unnecessary performance hit (compared to use ^ with the original property).

BTW if we do have the hygiene test against my objections I'd argue that a superproperty inverse should be sufficient. 
Let's consider a subPropertyOf b. b subPropertyOf c. d inverseOf c. Should this not pass the test? To take a practical example:
hasFloatingLeg subProperty of hasLeg. hasSwap inverse of hasLag should be OK without requiring a specific inverse of hasFLoatingLeg. What on earth would it be called? In what universe would that be meaningful to a business user?

**Comment by mereolog** [comment]
Shall I then modify the ontology guide so that there is ambiguity as to whether this is recommended as a hygiene test candidate?

**Comment by trypuz** [comment]
This test is OK, of course, as WARN not ERROR. @ElisaKendall, I do not suggest to output these warnings into a separate file; Jenkins provides already an apparent list of warnings (see, e.g., https://jenkins.edmcouncil.org/blue/organizations/jenkins/fibo/detail/PR-1197/1/pipeline/19 - expand the tab "/publisher/publish.sh hygiene").

**Comment by mereolog** [comment]
What about issuing INFO-level message as suggested in https://github.com/edmcouncil/ontology-publisher/issues/20?

**Comment by ElisaKendall** [comment]
Hmmm... It would depend on what cases you would use to demonstrate that something is missing.  For example, I agree with Pete that if there is a superproperty with an inverse, we shouldn't need it on the subproperty necessarily.  Also, there are patterns where we shouldn't need inverses, such as cases where the property identifies a feature of something, i.e. 'has x', where in many cases an inverse is not appropriate.

Cases where an inverse might be appropriate, but missing, include properties whose names do not start with 'has' (i.e., real verbs) - maybe run a test for these and see what you come up with before we decide one way or another?

**Comment by mereolog** [comment]
Here it is - I run the following query over Prod:
```
prefix owl:   <http://www.w3.org/2002/07/owl#> 
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?property
FROM <https://edm-council.linked.data.world/d/current-fibo-production-release/>
WHERE
{
?property rdf:type owl:ObjectProperty .
FILTER (CONTAINS(str(?property), "edmcouncil"))
FILTER NOT EXISTS {{?property owl:inverseOf ?inverse} UNION {?inverse owl:inverseOf ?property}}
FILTER NOT EXISTS {?property rdfs:subPropertyOf+ ?super . {{?super owl:inverseOf ?super_inverse} UNION {?super_inverse owl:inverseOf ?super}}}
} 
```
The query is rather "sparse", in the sense that it ignores all properties whose inverses can be inferred either from superproperties or from "inverser of their inverses"


The query found 300+ object properties.
[missinginverses_prod.xlsx](https://github.com/edmcouncil/fibo/files/5769484/missinginverses_prod.xlsx)
