### ISSUE TITLE
Listed security is improperly inferred to be a listing

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1244]
This is due, I think, because of a restriction on listed security that says it is identified by a ticker symbol, but a ticker symbol is asserted to identify a listing. This needs to be sorted out, as the references are circular at present.

The ticker symbol actually identifies the listed security, whereas the listing provides the registration details about the security. The ticker may or may not be used as a key into the registration information (i.e., the listing), so there may be an association, but it identifies the security.

**Comment by rivettp** [comment]
No I think the Ticker identifies the Listing, i.e. the Security on a specific Exchange.

**Comment by ElisaKendall** [comment]
I checked with Bruce, that's not the case.  The listing provides the registration detail for the security, but is not the security.  The ticker is an identifier for the security.  He has one - he filed all of that with Nasdaq for his bank.

**Comment by ElisaKendall** [comment]
That's what one of my early investors from Sandpiper also said - the ticker identifies the listed security, not the listing, which is a record that is maintained by the exchange about the listed security.

**Comment by ElisaKendall** [comment]
The inferences were saying that the listing and listed security were the same thing, which I knew was wrong in any case.

**Comment by jfgemski** [comment]
That sounds correct.

**Comment by rivettp** [comment]
Seems to me a Ticker is like a product code at Amazon - it represents the product as available through Amazon. You could buy the identical product at Target too but there it has a different product code.
FWIW on schema.org this notion is modeled as an Offer https://schema.org/Offer.
We should not be focusing on whatever "record" Amazon and Target may have about the product.

Since we define ListedShare/Security as the instrument listed on MANY exchanges.

Let's look at FIGI which is more precise. We have: 
	<owl:NamedIndividual rdf:about="&fibo-sec-eq-eqind;BBG00JPR0LX8">
		<rdf:type rdf:resource="&fibo-sec-sec-idind;FinancialInstrumentGlobalIdentifier"/>
		<rdfs:label>BBG00JPR0LX8</rdfs:label>
		<skos:definition>Financial Instrument Global Identifier (FIGI) for Apple Inc. common shares listed in the London Stock Exchange</skos:definition>
		<lcc-lr:hasTag>BBG00JPR0LX8</lcc-lr:hasTag>
		<lcc-lr:identifies rdf:resource="&fibo-sec-eq-eqind;XLOMListedAppleIncCommonStock"/>
	</owl:NamedIndividual>

which references:
	<owl:NamedIndividual rdf:about="&fibo-sec-eq-eqind;XLOMListedAppleIncCommonStock">
		<rdf:type rdf:resource="&fibo-sec-sec-lst;Listing"/>
		<rdfs:label>XLOM-listed Apple Inc. common stock</rdfs:label>
		<skos:definition>Apple Inc. common share listed in the London Stock Exchange</skos:definition>
		<fibo-fnd-acc-cur:hasCurrency rdf:resource="&fibo-fnd-acc-4217;USDollar"/>
		<fibo-sec-sec-lst:isTradedOn rdf:resource="&fibo-fbc-fct-mkti;Exchange-XLOM"/>
		<fibo-sec-sec-lst:lists rdf:resource="&fibo-sec-eq-eqind;AppleIncCommonStock"/>
	</owl:NamedIndividual>

This represents the Offer, which is a real business thing, not some sort of "record".
If there is a change needed it's to change the definition of Listing to replace "registry entry for a security" to "offer of a security". And maybe even change its URI?

**Comment by rivettp** [comment]
Back to the original bug, it's the restriction on ListedSecurity isIdentifiedBy TickerSymbol that's problematic. It should be a restriction on isListedVia some Listing.
