### ISSUE TITLE
Need the role of managing member associated with an LLC

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1264]
An LLC is a common kind of private company with limited liability, at least in the US and actually elsewhere in the world. LLCs have members and in some cases, at least one managing member.  The more specific definitions for LLC, LLC taxed as a corporation, and the definition of a managing member are missing, and should be added to BE.  Limited companies also exist in the U.K., Ireland, and Canada, among other countries, are called 'private limited company', and the abbreviation used for these kinds of companies is 'Ltd.'.  This class is also missing and should be added to BE given its prevalence.

**Comment by rivettp** [comment]
What's the use case here? For example LLC in US has specific ownership rules, as do S Corporations. Do the rules need to be modeled?

FWIW, speaking as a LLC Member, "Managing Member" has no legal meaning, at least in California. I sometimes call myself that because it sounds better.

We've agreed that FIBO should not try to tackle taxation, so IMO "taxed as a corporation" should be out of scope.

Also I think LLC in US is quite different from Ltd in UK. Whether we care depends on use case again.

WHY DO WE SAY USE CASES ARE IMPORTANT AND THEN PROPOSE SO MANY CHANGES WITHOUT EVEN A SEMBLANCE OF ONE?

**Comment by ElisaKendall** [comment]
One of the use cases for this is AML, another is KYC, both of which Robert and Harsh are working on and which include these concepts.  I need them for another use case that involves counterparty risk at a client organization.  They appear in applications for loans, among other things, and in some states, the role of managing member actually does have legal meaning, including the ability to enter into contracts on behalf of the organization.  Without that designation, all of the members of the LLC need to sign some contracts.  There are a couple of different kinds of LLCs - those that are member managed, like Thematix, with a designated managing member, and those that have a 3rd party manager.  I don't know the legal ins and outs of the latter, but for us, Rob is our managing member and signs contracts on our behalf.  

LLC is indeed different from Ltd - we need both concepts, both of which are subclasses of private company with limited liability.

**Comment by rivettp** [comment]
This is one of the better summaries https://legaltemplates.net/resources/business/llc-member-vs-manager/ though the taxation bit at the end does not apply in many cases. According to that, the 2 types are Member Managed or Manager Managed where the Manager may or may not also be a Member (hence Managing Member). The default in most US States is Member Managed (with no Managing Member) so I would technically be incorrect to use that designation for myself (not that it matters since we're taxed as an S Corp).

As far as I can see, not only are we missing Managing Member we are missing the notion of (LLC) Member completely (and LLC Manager). I think there is a legal difference between being a Member and regular Ownership, but do we have a use case that cares about the difference? Here is an example that could potentially make use of Member &fibo-fbc-fct-usind;CiticorpLLCOwnership. CitigroupInc-US-DE would be a Member but (as it's a single member LLC) not a Managing Member.

Also if we covering US-specific types of company should we not also have S Corporation? What about Benefit Corporation? Other types of not-for-profit?

As I know you're aware, "AML" or "KYC" is hardly the definition of a use case, though I expect that if Robert is involved, he will ensure a fuller use case definition got produced. There are lots of quite different things one could try to achieve in those areas, which would determine the competency questions and hence the detail needed in ontologies.  Prior to the use case definition, at least in outline, does it make sense to try to address this issue?

**Comment by ElisaKendall** [comment]
I agree that we are missing LLC, missing C-LLC, and missing Ltd. - I'm planning to add those under this issue.  They are not corporations, just as partnerships are not corporations, so this is a gap for a very common kind of business entity.  I can add both member managed and manager managed if you think that is needed, but hadn't planned to do so yet.  The only point was to add these organizations, which are not only common but are the typical form that funds and many bank entities take.

We actually do have Benefit Corporation, but not S Corporation.

**Comment by rivettp** [comment]
The member managed distinction is important only if we need Managing Member which this issue purports to be about.
BTW what's a C-LLC?

**Comment by ElisaKendall** [comment]
I think we do need managing member, since it came up in the AML context, so I'll add them.  A C-LLC is an LLC taxed as a corporation.  There must be some tax reason why someone would make that election, but guessing it only happens in the case of larger LLCs, maybe funds that don't want to distribute revenues as schedule K-1s.

**Comment by rivettp** [comment]
I've never heard of the term "C-LLC" and could not find it on Google either. 
It is possible to have different types of taxation for a LLC (including being taxed as different types of Corporation - my own LLC is taxed as a S Corporation) but we made the deliberate decision not to get into taxation in FIBO.
