### ISSUE TITLE
Interpretation of T1 candidate test

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1289]
I wonder what test candidate T1 is supposed to do - see: https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t1-creating-the-relationships-such-as-is-isa-isakindof--or-similar-rather-than-using-rdfssubclassof-rdftype-or-owlsameas.

The idea is, I believe, that we should avoid having the isA relation as an object property. But if this condition is to be automated, then we should be able to find some pattern, either in resources' IRIs or in their rdfs:labels, of such cases.

A simple search for object properties whose local name is 'is' finds nothing in the current FIBO Dev:
```
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?warning ?resource
WHERE 
{
    FILTER (CONTAINS(str(?resource), "edmcouncil"))
    FILTER (STRENDS(LCASE(str(?resource)),"is"))
    BIND (concat ("WARN: Resource ", str(?resource), " looks like the isA relation. ") AS ?warning) 
}
```
Are there any other patterns we should search for?

Frankly, this candidate seems to me a red herring candidate, i.e., it may be useful principle, but we might not be able to automate it.

**Comment by ElisaKendall** [comment]
@mereolog Hi Pawel, I -think- we included this because there were a number of cases of this in the original model that Mike created in UML that were then translated to OWL.  In a quick search of all of FIBO, it seems that we have eliminated cases of "isA", but I did find "isAlso", "isAlso.1", "mayBe", "mayBecome", "mayIncludeDetailsAbout", "mayRequire", "mayBeVariedByOne", "mayBeTradedIn" (which is in prod and needs to get fixed), "mayBeSubordinatedTo" (also in prod and needs to get fixed), "mayAlsoBe", "mayBeDefinedIn" ... so perhaps we can revise the test to look for these cases?  And make it a warning until I get rid of the two cases in prod?
