### ISSUE TITLE
New Hygiene Tests - T2 Test Candidate

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1290]
[T2 test candidate](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t2-creating-disconnected-ontology-elements) suggests that all FIBO classes should be rooted either in FND, BE or FBC.

The query below finds all cases where a top-level class has its location in a different domain:
```
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:   <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?warning ?class ?domainIdentifier
WHERE 
{
    ?class a owl:Class .
    FILTER NOT EXISTS {?class rdfs:subClassOf ?classParent}
    FILTER (CONTAINS(str(?class), "edmcouncil"))
    BIND (STRBEFORE(STRAFTER(str(?class),"https://spec.edmcouncil.org/fibo/ontology/"),"/") As ?domainIdentifier)
    FILTER (?domainIdentifier NOT IN ('FND', 'BE', 'FBC'))
    BIND (concat ("WARN: Class ", str(?class), " is a top-level class outside FIBO foundations.") AS ?warning)
}
ORDER BY ?domainIdentifier
```
In DEV the query found 50+ such disconnected classes: [disconnected_classes_in_fibo_dev.xlsx](https://github.com/edmcouncil/fibo/files/5787559/disconnected_classes_in_fibo_dev.xlsx)

I would propose adding this as a new hygiene test or dropping its description from the ontology guide.

We could also have a similar query for objects properties - although the guide does not seem to consider this option.

**Comment by ElisaKendall** [comment]
@merelog - Ultimately I would like every class to be rooted in FND (or LCC), but we are not quite there yet.  In Prod there are 4 classes rooted in FBC, none in BE, so maybe test for LCC, FND, and FBC at the moment.  The 4 classes rooted in FBC could be moved to FND, but they are widely used so I'll have to bring it up in the FBC/SEC FCT to see what kind of reaction I get to that before we do so.  They are fairly fundamental - Principal, Exposure, Offering, and most importantly, Account.  If we move them, we should do so before we pull the trigger on the OMG FIBO specification.  I think moving Principal, Exposure, and Offering to FND would be straightforward since there are not a lot of dependencies on them.  Account is more of a challenge.

For properties it will take more work to get there.  We have one in DER, three in IND, and quite a few in SEC.  Many but not all of these should be subproperties of something in FND, BE, or FBC, though, and there are a gazillion in Dev that are disconnected.
