### ISSUE TITLE
Interpretation of T4 Candidate Test

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1292]
The description of [T4 candidate test](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t4-merging-different-concepts-in-the-same-class) is rather sparse.

Prima facie, it sort of suggests that the resources under suspicion are those whose local names are "conjunctions" or "disjunctions" of the local names of other resources.
 
Is the mere presence of 'and' or 'or' connective in the local name is a sufficient ground for a resource being put under scrutiny?
Are the "component" resources, i.e., the ones mentioned in the suspicious name, need to refer to any resource whatsoever or just to FIBO resources?

**Comment by ElisaKendall** [comment]
@mereolog I think anything whose local name includes a conjunction or disjunction is suspicious.  We were forced to do that in a couple of cases for subclasses of account to support schema.org, which you could make exceptions, but otherwise this practice should be disallowed.

Aside from those two, did you find others?

**Comment by mereolog** [comment]
@ElisaKendall No, I did not.

**Comment by ElisaKendall** [comment]
@mereolog Is it possible to add a test that disallows the use of a conjunction or disjunction in a class name or property name, but make an exception for those two?  I'll see if I can come up with alternative names for those classes after reaching out to a couple of bankers, leaving the current names as synonyms, but if we do that you would also need to update the schema.org mapping.  Not sure how simple that would be to do or how many months it would take.  We would probably have to deprecate the originals rather than eliminate them for some period of time.

**Comment by mereolog** [comment]
@ElisaKendall I am afraid you lost me: which two ("but make an exception for **those two**")?

**Comment by ElisaKendall** [comment]
@merelog There are two classes in production that include a disjunction in the class name that I am aware of, including: InvestmentOrDepositAccount and LoanOrCreditAccount.  They were added explicitly to support schema.org, and so they are 'grandfathered in'.  I really don't like the names but am not sure we should change them given the 1-1 mapping to schema.org.  So if we add this test, we would need to make an exception for those two classes in the test.
