### ISSUE TITLE
New Hygiene Test - T11 Use of "min 1" cardinality restrictions

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1293]
To implement [T11 candidate test](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t11--use-of-min-1-cardinality-restrictions) we may run the following query:
```
prefix owl:   <http://www.w3.org/2002/07/owl#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

##
# banner "min 1" cardinality restrictions should be avoided.

SELECT DISTINCT ?error ?cardinality
WHERE {
  ?restriction  rdf:type owl:Restriction.
  {{?restriction owl:minQualifiedCardinality ?cardinality} UNION {?restriction owl:minCardinality ?cardinality}}.
  ?class rdfs:subClassOf ?restriction .
  FILTER (CONTAINS(str(?class), "edmcouncil"))
  FILTER (?cardinality = 1)
  BIND (concat ("WARN: OWL class", str(?class), " is a subclass of a restriction of type owl:minCardinality or owl:minQualifiedCardinality 1") AS ?error)
}
```
At the moment this quest returns 0 results in Dev, but it might useful to watch over future developments of FIBO.

Alternatively, it should be removed from the Ontology Guide.

**Comment by ElisaKendall** [comment]
@mereolog Please add this as a test, which should result in an error wherever it occurs.  It took a lot of work to eliminate all of the cases I ran across, and we really want people to use someValuesFrom instead, unless there is a very good reason for them to do otherwise.  There is a semantic difference, albeit a small one - they are not quite syntactic sugar from a reasoning perspective, but from all other viewpoints they are equivalent, and the distinction is not sufficiently useful IMHO to warrant using min 1 unless someone can prove that it is necessary for a specific use case.
