### ISSUE TITLE
CIV moved under SEC

### ISSUE THREAD

**Issue by jziemer2** [edmcouncil/fibo#1322]
Don’t you consider Alternative Investment Funds (as defined in AIFMD, 2011/61/EU) a FIBO Collective Investment Vehicle?
Per the release notes, “we moved what was a separate CIV (and special purpose vehicles) domain area under Securities.”  
The move fits ETFs, REITs, and Mutual or Unit Funds, but not unlisted Hedge, PE, and CTA. They offer partnerships – not securities.
You may end up pullings CIV back out of SEC in the future.
Also, users may confuse the prefix component “fnd” (= fund) in fibo-sec-**fnd** with Foundation. I would spell out “funds” as you did with “loans.”

**Comment by ElisaKendall** [comment]
@jziemer2 I thought about the point you've made with respect to the prefix - will discuss that and your point about the various Hedge funds that are unlisted, etc. on our SEC call tomorrow.  We moved them to SEC because that's how Citi, who participate in our calls, modeled them internally and it was their suggestion that people will look for them under SEC.  I think the hierarchy Mike Atkin originally developed had them under Securities as well.  Most of the banks we support have not been concerned about the partnership side of things, and it is outside the use cases we have at the moment, but I can certainly ask the question.

**Comment by ElisaKendall** [comment]
@jziemer2 On our SEC call this morning we agreed to modify the prefix, so I will do that under this issue, and change it to fibo-sec-fund-fund and fibo-sec-fund-civ.  The name of the CIV ontology will also change from CIV to CollectiveInvestmentVehicles, per our stated policy (what is there was a legacy name, which we moved straight across but had not revised to meet our policy).  

The consensus was that we should retain these two ontologies in their own subdomain of SEC, where they are now, even though the definition of SpecialPurposeVehicle is as a subclass of LegalEntity.  That's already in the Funds ontology, fyi, as is the notion of a fund taking a legal form, which may be that of a legal entity or may be that of a contract.  

We did note that there may be additional considerations once we start looking at structured products, which may result in a third ontology in this sub-domain, fyi.
