### ISSUE TITLE
ContractParty in LegalPersons

### ISSUE THREAD

**Issue by trypuz** [edmcouncil/fibo#1331]
This code is in [LegalPersons.rdf](https://github.com/edmcouncil/fibo/blob/master/BE/LegalEntities/LegalPersons.rdf)
```
	<owl:Class rdf:about="&fibo-fnd-agr-ctr;ContractParty">
		<rdfs:subClassOf>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&fibo-fnd-rel-rel;hasIdentity"/>
				<owl:onClass rdf:resource="&fibo-be-le-lp;LegalPerson"/>
				<owl:qualifiedCardinality rdf:datatype="&xsd;nonNegativeInteger">1</owl:qualifiedCardinality>
			</owl:Restriction>
		</rdfs:subClassOf>
	</owl:Class>
```
Shouldn't we move it into Contracts Ontology?

**Comment by ElisaKendall** [comment]
@trypuz This restriction is in LegalPersons because it says that a contract party is a legal person, which is in BE.  So to avoid a circular dependency and a dependency on BE in FND, we added it here.  It is true that a contract party must be a legal person, so we could alternatively merge FND and BE, but ... that's a pretty big change.  There are reasons that I've thought we might consider this over the years, just had not achieved consensus around it.  Actually, merging FND, BE, and FBC might have made sense, but again, we never achieved consensus around that.

**Comment by jfgemski** [comment]
@trypuz <https://github.com/trypuz>  I believe it’s ok as it is.  I can be a legal person independent of any contract requirements.  For example, I need to be a legal person to get a passport and each US legal person must file taxes.  FND properly defines the basis of a legal person.  BE is restricting a contract party in that a contract party must be a legal person.  

 

John

 

Jfgemski@gmail.com <mailto:Jfgemski@gmail.com>  | M: (516) 353-0004

**Comment by trypuz** [comment]
@ElisaKendall & @jfgemski - thank you for the explanation.
