### ISSUE TITLE
The concepts in the provisional credit facilities ontology should be integrated with the Debt ontology

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1424]
Many debt instruments are credit facilities, and the current representation would require the subclass relationship to be applied in a separate ontology. Since there are no new properties and a small number of classes defined in the provisional credit facilities ontology, it makes more sense to merge that with debt than to retain it as a separate ontology.

Also, a promissory note is a negotiable instrument and typically there is at least one promissory note associated with a credit facility. The promissory note class should be moved from contracts to debt and revised to say that it is a negotiable debt instrument, as well as adding the restriction on credit facility.

**Comment by tahoeblue** [comment]
The notion of “debt” instrument is itself a bit one-sided.  For example, to the person or entity that purchases a municipal bond, that “debt” instrument is actually an asset, not a liability — and which is not a credit facility, unless the term “credit facility” is defined much more broadly than is typically the case in banking (in which a credit facility is something that extends credit from the bank to the counterparty as a borrower ).  The only way to interpret the purchase of a municipal bond by an investor as a “credit facility” would be to assert that the investor is providing such a facility to the municipality that issued the bond (which seems upside down).   Also, a credit facility as an agreement (or “arrangement”, or contract) between two parties behaves differently than a single “debt instrument” that typically expresses a single amount that is borrowed (or invested) and usually has a well-defined interest and principal payment structure.  Credit facilities, in general, are much less deterministic since the cash flows over the life of the facility are very much dependent on the discretionary actions of the borrower.  I’m not sure how this affects the overall organization of the hierarchy, but — even though the act of funds becoming “indebted” between two parties, these two types of instruments  (e.g., municipal bonds and business credit lines) would appear to be different types of arrangements.  One could argue, for example, that a credit facility is a variation of a debt instrument, not the other way around.

**Comment by ElisaKendall** [comment]
@tahoeblue All of this is true.  I think my notes, above, were somewhat terse - the integration of credit facilities with the debt ontology doesn't make the debt instrument class a subclass of credit facility.  As you'll see once I upload the changes, credit facility is a sibling of debt instrument, both of which are subclasses of credit agreement.  Hopefully it will make more sense once you see what I've done, based on discussions with John Gemski and Bruce, among others.
