### ISSUE TITLE
Elements and jurisdictions should point to the current UN name for countries

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1467]
LCC includes legacy countries for the US, UK, and Czech Republic, and should instead reference the primary version for better query efficiency.  For example, for the U.S., in some cases we use UnitedStates and in others UnitedStatesOfAmerica.

**Comment by jfgemski** [comment]
Part of the problem is which code set you use.  For example, in the ISO 3166-1 code set U.S. is “United States of America”.  In the UN/LOCODE code set ( <https://unece.org/trade/cefact/unlocode-code-list-country-and-territory> https://unece.org/trade/cefact/unlocode-code-list-country-and-territory) U.S. is listed as “United States”.  My recommendation is that we standardize on the ISO 3166-1 code set.

 

John

 

***@***.*** ***@***.***>  | M: (516) 353-0004

 

From: Elisa Kendall ***@***.***> 
Sent: Thursday, March 25, 2021 6:58 PM
To: edmcouncil/fibo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [edmcouncil/fibo] Elements and jurisdictions should point to the current UN name for countries (#1467)

 

LCC includes legacy countries for the US, UK, and Czech Republic, and should instead reference the primary version for better query efficiency. For example, for the U.S., in some cases we use UnitedStates and in others UnitedStatesOfAmerica.

**Comment by ElisaKendall** [comment]
@jfgemski Agreed - that's exactly what I'm working on for this.
