### ISSUE TITLE
Class https://spec.edmcouncil.org/fibo/ontology/SEC/Funds/Funds/CollectiveInvestmentVehicle is unsatisfiable

### ISSUE THREAD

**Issue by liviorobaldo** [edmcouncil/fibo#1524]
Dear all,

my name is Livio Robaldo and I am a researcher in Computational Law at the Legal Innovation Lab Wales at Swansea University. I am new to this community, I started using FIBO as we have a research collaboration with an industrial partner working in the fund investment domain. I'm glad to contribute to FIBO development. 

I found out that the class CollectiveInvestmentVehicle is unsatisfiable, meaning that the ontology is consistent only when the extension of this class is the empty set. As such, the class is not much useful. In fact, Suppose we add an individual "test" to this class:

- "test rdf:type CollectiveInvestmentVehicle"

Then, since there are these two restrictions on the class CollectiveInvestmentVehicle:

- "CollectiveInvestmentVehicle SomeValuesFrom[fundHasRelatedParty FundsProcessingParty]"
- "CollectiveInvestmentVehicle SomeValuesFrom[hasFundIdentification OrganizationIdentifier]"

"test" is associated with other two individuals in FundsProcessingParty and OrganizationIdentifier. These are not explicitly asserted (but the ontology is nonetheless consistent because of the Open World Assumption), so for the sake of explanation let me simply call them unk1 and unk2. It holds:

- "unk1 rdf:type FundsProcessingParty"
- "unk2 rdf:type OrganizationIdentifier"
- "test fundHasRelatedParty unk1"
- "test hasFundIdentification unk2"

Now, since it holds:

- "fundHasRelatedParty SubObjectPropertyOf hasRelatedPartyInRole"
- "hasRelatedPartyInRole rdfs:domain PartyInRole"
- "PartyInRole rdfs:subClassOf AgentInRole"

"test" is inferred as a member of the class AgentInRole:

- "test rdf:type AgentInRole"

On the other hand, since it also holds:

- "hasFundIdentification SubObjectPropertyOf isIdentifiedBy"
- "isIdentifiedBy InverseObjectProperties identifies"
- "OrganizationIdentifier ExactCardinality_1[identifies Organization]"

"test" is also inferred as member of the class "Organization" (this does not appear to be correct, of course, "test" is a CollectiveInvestmentVehicle):

- "test rdf:type Organization"

In fact, if "unk2" is an "OrganizationIdentifier", "unk2" identifies "test", and an organization identifier can identify _exactly one_ organization, "test" must necessarily be an organization.

Now the ontology is inconsistent because it holds:

- "Organization rdfs:subClassOf IndependentParty"
- "IndependentParty owl:disjointWith AgentInRole"

In other words: "test" cannot be an IndependentParty and an AgentInRole at the same time.

To fix the error, I suggest to remove this restriction:

- "CollectiveInvestmentVehicle SomeValuesFrom[hasFundIdentification OrganizationIdentifier]"

A CollectiveInvestmentVehicle should be *not* identified with an OrganizationIdentifier...

===================

I found out that CollectiveInvestmentVehicle is unsatisfiable by adding individuals to the ontology (I'm using NLP to extract data from financial documents and populating the ontology, i.e., entity linking) and then by running the HermiT reasoner. By the way, HermiT takes half a day to explain the inconsistency, as the ontology is very big, so maybe I/we should use a faster reasoner...

However, it is likely that there are other unsatisfiable classes. I see you defined some "hygiene tests", maybe you can add one to search for unsatisfiable classes by adding dummies individuals in the ontology.

Hope this helps
Livio

**Comment by ElisaKendall** [comment]
Hi Livio, 

This is a nice catch.  The Funds ontology is a recent addition to the set of released ontologies, and we have not yet had the bandwidth to test it extensively.  I'll add this to our queue to fix.  Although your idea of adding test data is a good one, and we've done this for some cases, with examples, we haven't had the resources to build out test data for every class.  I don't see that happening any time soon, but appreciate the thought and that you found this.

Best,

Elisa

**Comment by ElisaKendall** [comment]
Also, if you would like to get involved, we have 3 working groups that meet weekly - securities (which this falls under), derivatives, and indices and indicators.  I'd be happy to invite you to any of them - just let me know what interests you the most (or all 3 if you have the bandwidth).  Thanks!

**Comment by liviorobaldo** [comment]
Dear Elisa, 

Sure, I'm happy to help building the ontology about "securities", but I'm not much knowledgeable of the domain: I'm an IT guy, expert in NLP and KR, I'm not a financial advisor expert in the investment funds domain. Thus, I don't know how much I can truly help to model knowledge in this domain... and you say that the working group has a bandwidth, do you mean there is a cap on the max number of participants? Nevertheless, for sure I can help on the IT side, as I want to use the ontology: whenever I catch inconsistencies or redundancies I will let you know.

On the other hand, as you can see in the discussions section, I would like to know if FIBO is concerned with the mapping between concepts and texts. I see there are (few) datatype properties to connect concepts with textual spans, but indeed a real application would need more. For instance, the individuals in FundProspectus should be associated with the several sections in a prospectus or a KIID (objective and investment policy section, risks sections, etc.).

Thanks
Livio

**Comment by ElisaKendall** [comment]
@liviorobaldo Hi Livio, 

I've spent a bit of time debugging this, and it looks like the latest version of the ontology does not include these restrictions.  We've modified the representation of CollectiveInvestmentVehicle, probably more recently than the version you downloaded, and these restrictions are no longer there.  There is one thing that may be an issue, which is that PooledFund is a subclass of FinancialAsset - theoretically one can create a fund before it has investors, though most funds and managed investments are only of interest once they do have investors.  If you found this in the Q1 2021 production release, that wouldn't surprise me, but we've made a few revisions since to clean things up.  Those revisions will be published officially in the Q2 2021 release, but you could download the latest version from GitHub to see the changes.  If you have the bandwidth to do so, would you please use the latest version in GitHub and retry your test with respect to creating individuals - that would be very helpful to us, and we would be happy to address any outstanding issues.

There are other folks using FIBO with NLP, or at least are experimenting with it, including vendors, but I am not aware that any of them have provided use cases back to us.  We recently addressed an issue to expand our representation of contract, for example, to include some additional standard clauses and the relationships to those.  To my knowledge no one has asked for the same with respect to Prospectus, and we would need an attorney or two as subject matter experts in securities issuance to assist us with that.

We will add you to the meeting invitation for SEC - we're taking a break for the U.S. Memorial Day holiday next week, so our next meeting will be on June 7th.  Happy to have you participate.

Best regards,

Elisa

**Comment by liviorobaldo** [comment]
Dear Elisa,

I'm afraid I didn't understand much of what you wrote in the first part of your message :-(
I downloaded the ontology from here:

https://edmconnect.edmcouncil.org/fibointerestgroup/fibo-products/fibo-owl

As I read "FIBO Development is published in real-time as changes are incorporated by the FIBO Community and consists of a draft as well-vetted content". 

Which ontology should I download instead?

Thanks
Livio

**Comment by ElisaKendall** [comment]
Hi Livio,

For fully vetted ontologies on that same link, you should download the FIBO production ontologies rather than development.  We guarantee that the production versions are logically consistent, but there is no such guarantee with the development version.  The most recent production version was published at the end of Q1 2021, so either on March 31 or shortly thereafter.  There is less content, as you might expect, but the terms and definitions have at least been reviewed and the ontologies are consistent.  If you want "everything", warts and all, and not guaranteed to be consistent, feel free to use the development version, but as I said there is no guarantee that they are consistent, or even that the extensions will remain in the same structure or form that you find them over time.  You can tell if an individual ontology is part of the production version if the maturity annotation has a value of Release, fyi.

If you would like to learn more about what we have in GitHub and how to load those ontologies in Protege, etc., please don't hesitate to ask - I'm happy to share more.

Best,

Elisa

**Comment by liviorobaldo** [comment]
Dear Elisa,

Thanks a lot for the explanation! I am loading the ontologies on Protege already, as well as on Java to populate them.

Livio
