### ISSUE TITLE
The restriction on exchange that says it operates in exactly 1 municipality is too narrow

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1532]
It's possible that while an exchange is likely based in one country and within that country, in one municipality, it is possible given today's digital trading environment that it could operate in more than one location (even though the current set of MIC codes force a choice of a single location).

One example is NYSE Arca, whose parent organization is in New York, but that operates, or has operated in Chicago. Because our example conflicts with the MIC code representation, Chicago is inferred to be the same as New York, which is clearly not right.

**Comment by jfgemski** [comment]
I think the distinction you want to make is “primarily resides in” (the MIC code) and “operates in”.

 

John

 

***@***.*** ***@***.***>  |O: (516) 826-0701| M: (516) 353-0004

 

From: Elisa Kendall ***@***.***> 
Sent: Thursday, June 3, 2021 2:56 PM
To: edmcouncil/fibo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [edmcouncil/fibo] The restriction on exchange that says it operates in exactly 1 municipality is too narrow (#1532)

 

It's possible that while an exchange is likely based in one country and within that country, in one municipality, it is possible given today's digital trading environment that it could operate in more than one location (even though the current set of MIC codes force a choice of a single location).

One example is NYSE Arca, whose parent organization is in New York, but that operates, or has operated in Chicago. Because our example conflicts with the MIC code representation, Chicago is inferred to be the same as New York, which is clearly not right.
