### ISSUE TITLE
Incongruity in the identifier hierarchy

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1563]
Review of the identifier hierarchy across a number of FIBO domains identified the following issues:

1. Legal entity identifier, local operating unit identifier, and value-added tax identifier should be subclasses of registry identifier in addition to organization identifier.

2. A bank identifier should not be an organization identifier, but instead should be a financial service provider identifier (which identifies a party in role) and a registry identifier. This should result in a logical inconsistency but does not due to lack of disjointness axioms.

3. A passport number should be a subclass of national identification number and of registry identifier (currently neither).

4. A StatisticalAreaIdentifier should be a subclass of GeographicRegionIdentifier, and so should postcode and so should federal reserve district identifier.

These should be cleaned up so that the hierarchy makes more sense. A number of these identifiers are in FND, but bank identifiers and registry identifiers are defined in FBC, and so subclass relationships will need to be added in some cases in FBC.

**Comment by jfgemski** [comment]
Good catch.

 

John

 

***@***.*** ***@***.***>  |O: (516) 826-0701| M: (516) 353-0004

 

From: Elisa Kendall ***@***.***> 
Sent: Monday, August 2, 2021 1:21 PM
To: edmcouncil/fibo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [edmcouncil/fibo] Incongruity in the identifier hierarchy (#1563)

 

Review of the identifier hierarchy across a number of FIBO domains identified the following issues:

1.	Legal entity identifier, local operating unit identifier, and value-added tax identifier should be subclasses of registry identifier in addition to organization identifier.
2.	A bank identifier should not be an organization identifier, but instead should be a financial service provider identifier (which identifies a party in role) and a registry identifier. This should result in a logical inconsistency but does not due to lack of disjointness axioms.
3.	A passport number should be a subclass of national identification number and of registry identifier (currently neither).
4.	A StatisticalAreaIdentifier should be a subclass of GeographicRegionIdentifier, and so should postcode and so should federal reserve district identifier.

These should be cleaned up so that the hierarchy makes more sense. A number of these identifiers are in FND, but bank identifiers and registry identifiers are defined in FBC, and so subclass relationships will need to be added in some cases in FBC.

**Comment by tahoeblue** [comment]
Hi Elisa,

Not sure I agree with some of that.

For starters, some clarification of what is meant by “registry identifier” is needed.  Is that an identifier of a registrar, or an identifier issued by a registrar ?

A legal entity identifier is an identifier issued by a registrar, but a local operating unit identifier is an identifier of a registrar (and, in the GLEIF universe, is itself an LEI ).

More importantly, a bank identifier is, I would argue, an organizational identifier, although the type of organization can readily be subclassed as a financial service provider.  One can always assert that a bank has a party in role in financial services, and a bank identifier can be used to link to the organization that is a party in role — but surely a bank identifier does identify the organization, does it not ?

Looking to the future, if you are looking to subclass all identifiers as subclasses of registry identifier, you are going to run into problems with Self-Sovereign Identification (SSI), in which the identifier is not issued by a registrar.

Apologies for missing today’s meeting.

Best,

-Jeff

**Comment by ElisaKendall** [comment]
Hi Jeff,

 Yes to issued by a registrar, and in most cases that also qualifies as an index to other information about the registered entity.  I'll take another look at the LOU identifier and make sure that I do the right thing there - which might be to eliminate a separate identifier which we currently have.

The bank identifier in the ontology is one that is an IBAN number, defined per ISO 13616-1, and specifically identifies a financial institution for the purpose of transfer of funds - not a generic identifier for an organization.  An organization that is not chartered as a bank cannot have one, thus it applies to the role, not to the organization, as we've done for things like FDIC charters.

**Comment by tahoeblue** [comment]
Hi Elisa,

Thanks for the clarification regarding the bank identifier. I understand that the IBAN number can only be assigned to, or used by, an organization that is authorized to participate in a specific network for the purpose of performing financial transactions.  In that sense it is much like an account number for the institution. 

 I think a key distinction may be that this number is used as the address of a business unit within an organization — but it is my understanding that this identifier is in fact at the level of the legal liability of the organization — can a legal entity have more than one IBAN (i.e., like a BIC) ?.  

If not, I believe that it does identify the organization as well as associating certain capabilities to the organization.  it is not necessary that an identifier for organizations to be able to be assigned to every organization in order to be considered an organizational identifier, is it ?  

Best,

-Jeff

**Comment by ElisaKendall** [comment]
Hi Jeff,

I'll have to check on whether or not an institution (rather than organization) can have multiple IBAN numbers.  I think this is possible for a number of reasons, including but not limited to mergers and acquisitions, legal entity hierarchies (i.e., it is possible that a brokerage function in a large institution has a different IBAN number from the retail arm of the same institution - but I need to confirm that).  But only financial institutions can have such a number in the first place - the identifier goes with the function of transfering funds between institutions across national borders.

**Comment by ElisaKendall** [comment]
I've confirmed that a given institution can have multiple IBAN numbers.  The definition of the construction of an IBAN is as follows:

**The ISO 13616 IBAN Standard**
_Structure_
The IBAN structure is defined in ISO 13616-1 and consists of a two-letter ISO 3166-1
country code, followed by two check digits and up to thirty alphanumeric characters for
a BBAN (Basic Bank Account Number) which has a fixed length per country and,
included within it, a bank identifier with a fixed position and a fixed length per country.
The check digits are calculated based on the scheme defined in ISO/IEC 7064
(MOD97-10).

_Terms and definitions_
**Bank identifier:** The identifier that uniquely identifies the financial institution and,
when appropriate, the branch of that financial institution servicing an account
In this registry, the branch identifier format is shown specifically, when present.
**BBAN:** basic bank account number: The identifier that uniquely identifies an individual
account, at a specific financial institution, in a particular country. The BBAN includes a
bank identifier of the financial institution servicing that account.
**IBAN:** international bank account number: The expanded version of the basic bank
account number (BBAN), intended for use internationally. The IBAN uniquely identifies
an individual account, at a specific financial institution, in a particular country.

I believe that our current model supports this structure, but will confirm as a part of addressing this issue.

**Comment by tahoeblue** [comment]
Hi Elisa,

Thanks for the good info on the IBAN.  As it does identify a point of authorized processing of financial transactions within an organization, it functions much like a BIC in that regard.  The definition for “bank identifier” (below) is interesting, however, in that it does define that as an "identifier that uniquely identifies the financial institution”, although this unique identifier is included within the Basic Bank Account Number (BBAN).  You might want to take that into account when defining “bank identifier”, since, as the description below shows, is distinct from BBAN or IBAN.

**Comment by ElisaKendall** [comment]
Yup - will do.  There is also in some cases a mapping from the IBAN to the BIC code(s) when an IBAN is ambiguous, also discussed in some of the documents I found.  But the fact that it may identify not only an institution but a branch within that institution is what caught my attention.  I'll confirm that our model supports that.

**Comment by rivettp** [comment]
> For starters, some clarification of what is meant by “registry identifier” is needed. Is that an identifier of a registrar, or an identifier issued by a registrar ?
Good point, I think it's meant to be the latter though the name implies the former.
The definition says "an identifier associated with an entry in a registry, i.e., one that provides an index to the registry for the identified item"
though that's also misleading - for consistency with "associated with an entry" it should surely say "into the registry" rather than "to the registry".
And also the following restriction seems wrong: it should surely be onClass RegistryEntry not Registry.

                <owl:onProperty rdf:resource="&fibo-fnd-arr-id;isIndexTo"/>
                <owl:onClass rdf:resource="&fibo-fbc-fct-ra;Registry"/>
                <owl:minQualifiedCardinality rdf:datatype="&xsd;nonNegativeInteger">0</owl:minQualifiedCardinality>

especially since we also have the following (which is somewhat redundant since the RegistryEntry will reference the Registry. It could I guess be a property chain):
            <owl:Restriction>
                <owl:onProperty rdf:resource="&fibo-fbc-fct-ra;isRegisteredIn"/>
                <owl:someValuesFrom rdf:resource="&fibo-fbc-fct-ra;Registry"/>
            </owl:Restriction>

I see we don't use isIndexTo at all in the example individuals we have for LEIs. For example:

    <owl:NamedIndividual rdf:about="https://rdf.gleif.org/L1/L-KB1H1DSPRFMYMCUFXT09-LEI">
        <rdf:type rdf:resource="&fibo-be-le-lei;LegalEntityIdentifier"/>
        <rdfs:label>Wells Fargo Bank, National Association legal entity identifier</rdfs:label>
        <skos:definition>legal entity identifier for Wells Fargo Bank, National Association</skos:definition>
        <fibo-fbc-fct-ra:isRegisteredIn rdf:resource="&fibo-fbc-fct-usfsind;BloombergLEIRegistry"/>
        <lcc-lr:hasTag>KB1H1DSPRFMYMCUFXT09</lcc-lr:hasTag>
        <lcc-lr:identifies rdf:resource="&fibo-fbc-fct-usind;WellsFargoBankNationalAssociation-US"/>
    </owl:NamedIndividual>

We have the reference the other way round, using comprises. Though that's not the inverse of isIndexTo.
    <owl:NamedIndividual rdf:about="&fibo-fbc-fct-usind;WellsFargoBankNationalAssociationLegalEntityIdentifierRegistryEntry">
        <rdf:type rdf:resource="&fibo-fbc-fct-breg;LegalEntityIdentifierRegistryEntry"/>
        <rdfs:label>Wells Fargo Bank, National Association legal entity identifier registry entry</rdfs:label>
        <skos:definition>legal entity identifier registry entry for Wells Fargo Bank, National Association</skos:definition>
        <fibo-fbc-fct-breg:hasInitialRegistrationDate rdf:datatype="&xsd;dateTime">2012-06-06T15:53:00.000</fibo-fbc-fct-breg:hasInitialRegistrationDate>
        <fibo-fbc-fct-breg:hasRegistrationStatus rdf:resource="&fibo-fbc-fct-breg;IssuedStatus"/>
        <fibo-fbc-fct-breg:hasRegistrationStatusRevisionDate rdf:datatype="&xsd;dateTime">2020-09-22T20:32:05.021</fibo-fbc-fct-breg:hasRegistrationStatusRevisionDate>
        <fibo-fbc-fct-breg:hasRenewalDate rdf:datatype="&xsd;dateTime">2021-09-27T20:07:00.000</fibo-fbc-fct-breg:hasRenewalDate>
        <fibo-fbc-fct-breg:hasValidationLevel rdf:resource="&fibo-fbc-fct-breg;EntityValidationLevelFullyCorroborated"/>
        <fibo-fnd-rel-rel:comprises rdf:resource="https://rdf.gleif.org/L1/L-KB1H1DSPRFMYMCUFXT09-LEI"/>
        <lcc-cr:isPartOf rdf:resource="&fibo-fbc-fct-usfsind;BloombergLEIRegistry"/>
    </owl:NamedIndividual>

I'm not actually sure why the Identifier need be a separate individual from the RegistryEntry - they will always be one-to-one surely. In the data.world GLEIF dataset they are combined.

Jeff, a separate question for you arising from the above: would you really consider BloombergLEIRegistry to be a separate registry? Or is Bloomberg just one of many LOUs who manage a single global GLEIF LEI registry? The latter is how I modeled the data.world dataset. LOUs could in theory come and go, it's still the one global registry which is what matters, and within which the LEIs must be unique.
In the same way that there is one US-wide registry for SSNs despite the fact that (I believe) the different states handle the admin.
Unlike US driving licenses where there really are state-level registries and the identifiers are only unique within those.

Further following up it seems to me that as an LOU, Bloomberg is a Registrar not a RegistrationAuthority. GLEIF (or ROC?) is the RegistratationAuthority (who designates the LOUs).
    <owl:NamedIndividual rdf:about="&fibo-fbc-fct-usfsind;BloombergLP">
        <rdf:type rdf:resource="&fibo-fbc-fct-ra;RegistrationAuthority"/>
        <rdf:type rdf:resource="&fibo-fbc-pas-fpas;FinancialServiceProvider"/>
        <rdfs:label>Bloomberg L.P.</rdfs:label>
        <rdfs:isDefinedBy rdf:resource="https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/NorthAmericanEntities/USFinancialServicesEntitiesIndividuals/"/>
        <skos:definition>Bloomberg L.P. functional entity, which is a global business and financial information services and news provider as well as a FIGI registration authority</skos:definition>
        <fibo-fnd-rel-rel:hasIdentity rdf:resource="&fibo-fbc-fct-usfsind;BloombergLP-US-DE"/>
    </owl:NamedIndividual>

Further, if we're going to have roles as separate individuals (I don't really agree with), why not a separate individual for Bloomberg as  LOU vs Bloomberg as financial information service provider? Which, as a role, has nothing at all in common with LEI registration. How would we track the date that Bloomberg was made a LOU for example?

> A legal entity identifier is an identifier issued by a registrar, but a local operating unit identifier is an identifier of a registrar (and, in the GLEIF universe, is itself an LEI ).
Yes, but I believe there is also a code associated with each LOU that is (after the period of legacy registrations) used to construct the LEIs allocated by that LOU. Not sure how we model that. I think in general we still need to do general work on composite identifiers of which we have many including the IBAN as just described.

>  An organization that is not chartered as a bank cannot have one, thus it applies to the role, not to the organization, as we've done for things like FDIC
More generally there are many cases where there are conditions on who can have an identifier.
That does not mean the identifier has to be associated with a separate Role object. For example, to have a SSN you need to be a resident of the US. That does not mean we need a separate "USResident" PartyInRole.
To have a LEI there are various qualifications too (e.g. not a natural person). And you need to have paid the registration fee at least once.  But the LEI (rightly) identifies the LegalEntity not the role PaidUpLEIRegistrant.



Pete

________________________________

**Comment by ElisaKendall** [comment]
@rivettp Pete, Is there confirmation that there are no individual people (natural persons) that have LEIs?  Have those that were issued originally been recinded, and has the data been cleaned up to that effect?  If not, then the LEI applies to the legal person rather than to a legal entity (currently we have it on legal person, which is correct if human beings can in any corner case have one.

**Comment by rivettp** [comment]
I'll defer to Jeff on the immediate question about people having LEIs, but IMO it does not matter for this topic: my point was that the condition associated with being qualified for a specific registry may change over time. It's still a condition on the (Independent) Person (legal and/or natural) not on a Role. And the presence of a condition for a Registry does not by itself require the role to be the registered thing, as you seemed to be saying.

Pete
________________________________

**Comment by ElisaKendall** [comment]
For certain bank identifiers, the function is what the identifier points to - this is not necessarily a party in role, it is a function in which certain criteria must be inherent in order to qualify for the identifier.  An FDIC charter only applies to a depository institution - you can't have depository insurance unless you have qualified as a depository institution and are regulated as such.  That's a functional capability / role that the organization plays, although the same organization may play many other roles in addition to that of a licensed and regulated depository institution.

**Comment by tahoeblue** [comment]
Pete,

See my comments re the Bloomberg LOU below, in red.

> On Aug 2, 2021, at 2:26 PM, Pete Rivett ***@***.***> wrote:
> 
> 
> > For starters, some clarification of what is meant by “registry identifier” is needed. Is that an identifier of a registrar, or an identifier issued by a registrar ?
> Good point, I think it's meant to be the latter though the name implies the former.
> The definition says "an identifier associated with an entry in a registry, i.e., one that provides an index to the registry for the identified item"
> though that's also misleading - for consistency with "associated with an entry" it should surely say "into the registry" rather than "to the registry".
> And also the following restriction seems wrong: it should surely be onClass RegistryEntry not Registry.
> 
> <owl:onProperty rdf:resource="&fibo-fnd-arr-id;isIndexTo"/>
> <owl:onClass rdf:resource="&fibo-fbc-fct-ra;Registry"/>
> <owl:minQualifiedCardinality rdf:datatype="&xsd;nonNegativeInteger">0</owl:minQualifiedCardinality>
> 
> especially since we also have the following (which is somewhat redundant since the RegistryEntry will reference the Registry. It could I guess be a property chain):
> <owl:Restriction>
> <owl:onProperty rdf:resource="&fibo-fbc-fct-ra;isRegisteredIn"/>
> <owl:someValuesFrom rdf:resource="&fibo-fbc-fct-ra;Registry"/>
> </owl:Restriction>
> 
> I see we don't use isIndexTo at all in the example individuals we have for LEIs. For example:
> 
> <owl:NamedIndividual rdf:about="https://rdf.gleif.org/L1/L-KB1H1DSPRFMYMCUFXT09-LEI">
> <rdf:type rdf:resource="&fibo-be-le-lei;LegalEntityIdentifier"/>
> <rdfs:label>Wells Fargo Bank, National Association legal entity identifier</rdfs:label>
> <skos:definition>legal entity identifier for Wells Fargo Bank, National Association</skos:definition>
> <fibo-fbc-fct-ra:isRegisteredIn rdf:resource="&fibo-fbc-fct-usfsind;BloombergLEIRegistry"/>
> <lcc-lr:hasTag>KB1H1DSPRFMYMCUFXT09</lcc-lr:hasTag>
> <lcc-lr:identifies rdf:resource="&fibo-fbc-fct-usind;WellsFargoBankNationalAssociation-US"/>
> </owl:NamedIndividual>
> 
> We have the reference the other way round, using comprises. Though that's not the inverse of isIndexTo.
> <owl:NamedIndividual rdf:about="&fibo-fbc-fct-usind;WellsFargoBankNationalAssociationLegalEntityIdentifierRegistryEntry">
> <rdf:type rdf:resource="&fibo-fbc-fct-breg;LegalEntityIdentifierRegistryEntry"/>
> <rdfs:label>Wells Fargo Bank, National Association legal entity identifier registry entry</rdfs:label>
> <skos:definition>legal entity identifier registry entry for Wells Fargo Bank, National Association</skos:definition>
> <fibo-fbc-fct-breg:hasInitialRegistrationDate rdf:datatype="&xsd;dateTime">2012-06-06T15:53:00.000</fibo-fbc-fct-breg:hasInitialRegistrationDate>
> <fibo-fbc-fct-breg:hasRegistrationStatus rdf:resource="&fibo-fbc-fct-breg;IssuedStatus"/>
> <fibo-fbc-fct-breg:hasRegistrationStatusRevisionDate rdf:datatype="&xsd;dateTime">2020-09-22T20:32:05.021</fibo-fbc-fct-breg:hasRegistrationStatusRevisionDate>
> <fibo-fbc-fct-breg:hasRenewalDate rdf:datatype="&xsd;dateTime">2021-09-27T20:07:00.000</fibo-fbc-fct-breg:hasRenewalDate>
> <fibo-fbc-fct-breg:hasValidationLevel rdf:resource="&fibo-fbc-fct-breg;EntityValidationLevelFullyCorroborated"/>
> <fibo-fnd-rel-rel:comprises rdf:resource="https://rdf.gleif.org/L1/L-KB1H1DSPRFMYMCUFXT09-LEI"/>
> <lcc-cr:isPartOf rdf:resource="&fibo-fbc-fct-usfsind;BloombergLEIRegistry"/>
> </owl:NamedIndividual>
> 
> I'm not actually sure why the Identifier need be a separate individual from the RegistryEntry - they will always be one-to-one surely. In the data.world GLEIF dataset they are combined.
> 
> Jeff, a separate question for you arising from the above: would you really consider BloombergLEIRegistry to be a separate registry? Or is Bloomberg just one of many LOUs who manage a single global GLEIF LEI registry?

The latter is correct.   There is only one official registration authority, and that is the Global LEI Foundation (GLEIF).  The “LOUs” (literally, Local Operating Units) are part of a federated system that GLEIF accredits under its registration authority (i.e., as the “registry”) to issue LEIs.

> The latter is how I modeled the data.world dataset. LOUs could in theory come and go, it's still the one global registry which is what matters, and within which the LEIs must be unique.

Also correct, which is why each LOU is assigned a unique prefix with which to issue LEIs in order to guarantee the global uniqueness of the LEI, regardless of which LEI serviced the registrant.

> In the same way that there is one US-wide registry for SSNs despite the fact that (I believe) the different states handle the admin.

Good example of same ^^^^

> Unlike US driving licenses where there really are state-level registries and the identifiers are only unique within those.
> 
> Further following up it seems to me that as an LOU, Bloomberg is a Registrar not a RegistrationAuthority. GLEIF (or ROC?) is the RegistratationAuthority (who designates the LOUs).

GLEIF is the Registration Authority. the ROC has oversight.  (Literally, Regulatory Oversight Committee ).   And GLEIF is the registrar of last resort.

> <owl:NamedIndividual rdf:about="&fibo-fbc-fct-usfsind;BloombergLP">
> <rdf:type rdf:resource="&fibo-fbc-fct-ra;RegistrationAuthority"/>
> <rdf:type rdf:resource="&fibo-fbc-pas-fpas;FinancialServiceProvider"/>
> <rdfs:label>Bloomberg L.P.</rdfs:label>
> <rdfs:isDefinedBy rdf:resource="https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/NorthAmericanEntities/USFinancialServicesEntitiesIndividuals/"/>
> <skos:definition>Bloomberg L.P. functional entity, which is a global business and financial information services and news provider as well as a FIGI registration authority</skos:definition>
> <fibo-fnd-rel-rel:hasIdentity rdf:resource="&fibo-fbc-fct-usfsind;BloombergLP-US-DE"/>
> </owl:NamedIndividual>
> 
> Further, if we're going to have roles as separate individuals (I don't really agree with), why not a separate individual for Bloomberg as LOU vs Bloomberg as financial information service provider? Which, as a role, has nothing at all in common with LEI registration. How would we track the date that Bloomberg was made a LOU for example?
> 
> > A legal entity identifier is an identifier issued by a registrar, but a local operating unit identifier is an identifier of a registrar (and, in the GLEIF universe, is itself an LEI ).
> Yes, but I believe there is also a code associated with each LOU that is (after the period of legacy registrations) used to construct the LEIs allocated by that LOU. Not sure how we model that. I think in general we still need to do general work on composite identifiers of which we have many including the IBAN as just described.

No, the prefix issued to an LOU for the purpose of minting unique LEIs in a federated system is NOT an identifier of the LOU — it is just an LEI code partitioning mechanism similar to class A, B, and C Version4 IP addresses  In fact, and LOU could be issued more than one prefix if necessary.  An LOU, as an organization, is itself identified by its own LEI, not by some other unrelated code list.

> 
> > An organization that is not chartered as a bank cannot have one, thus it applies to the role, not to the organization, as we've done for things like FDIC
> More generally there are many cases where there are conditions on who can have an identifier.
> That does not mean the identifier has to be associated with a separate Role object. For example, to have a SSN you need to be a resident of the US. That does not mean we need a separate "USResident" PartyInRole.
> To have a LEI there are various qualifications too (e.g. not a natural person). And you need to have paid the registration fee at least once. But the LEI (rightly) identifies the LegalEntity not the role PaidUpLEIRegistrant.

Correct !

**Comment by tahoeblue** [comment]
Sole proprietorships (an individual acting in a business capacity ) can and are assigned LEIs.  The operative criteria is whether the sole proprietor (or owner/manager) has obtained a verifiable registration from an authoritative source to operate as a business.

The fact that, early on, some LEIs may have been issued to individuals without registering with a business registry can be considered exceptions to LEI policy, but that does not invalidate the policy nor reclassify the scope of LEI issuance. 

Furthermore, LEI issuance policy is a work in progress, and policy for extending LEI coverage to, for example,  governmental organizations at various levels of sovereign jurisdiction (e.g, federal, state, county, and municipality ) is currently under review by the ROC (which defines and revises such policies ).

More significantly, GLEIF has a number of mechanisms in the works for utilizing the LEI in connection with either organizational roles or personal identification.  

The first of these has to do with the CAB Forum recognizing the ability to include the LEI as part of the reference attributes of PKI certificates (i.e., the GLEIF acting as a Certificate Authority that authorizes a chain of trust to the legal entity to themselves issue certificates containing the LEI of the entity).  The legal entity can then issue certificates to individuals within the organization.  This linkage would allow the identification of both the legal entity and the trader for a variety of regulatory reporting compliance requirements involving the identification of both legal entity and person.

More fundamentally, and importantly, GLEIF has been developing a similar chain of trust based on Self-Sovereign Identification (SSI) in which cryptographically verifiable digital credentials are created for the purpose of trusted peer-to-peer interactions.  ( see trustoverip.org and keri.one ).

Best,

-Jeff
