### ISSUE TITLE
Inconsistent typing of hasJudgementAmount 

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1566]
hasJudgementAmount is typed as an object property, but it is also a subtype of hasAmount, which is a data property.

This makes FIBO not compliant with OWL 2 DL (https://www.w3.org/TR/owl2-new-features/#F12:_Punning) and introduces punning, which we implicitly condemn in https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#overarching-principles.

```
<owl:ObjectProperty rdf:about="&fibo-loan-ln-ev;hasJudgementAmount">
		<rdfs:subPropertyOf rdf:resource="&fibo-fnd-acc-cur;hasAmount"/>
		<rdfs:label xml:lang="en">has judgement amount</rdfs:label>
		<rdfs:domain rdf:resource="&fibo-loan-ln-ev;CourtJudgment"/>
		<rdfs:range rdf:resource="&fibo-fnd-acc-cur;MonetaryAmount"/>
		<skos:definition xml:lang="en">Undefined PoC SDM Notes: Total value of CCJs or equivalent recorded against the primary borrower that were satisfied / unsatsified (at time of underwriting ) is computed by selecting the satisfaction code value of interest and aggregating against all borrower CC Judgements &amp;lt;/p&amp;gt;</skos:definition>
</owl:ObjectProperty>
```

```
<owl:DatatypeProperty rdf:about="&fibo-fnd-acc-cur;hasAmount">
		<rdfs:subPropertyOf rdf:resource="&fibo-fnd-qt-qtu;hasNumericValue"/>
		<rdfs:label>has amount</rdfs:label>
		<rdfs:range rdf:resource="&xsd;decimal"/>
		<skos:definition>total number or quantity</skos:definition>
</owl:DatatypeProperty>
```

**Comment by ElisaKendall** [comment]
@mereolog Hi Pawel, 

This bug is in a provisional ontology - I can fix it but we don't make any claim that anything in our provisional ontologies is correct or consistent in any way, so that won't necessarily make this particular ontology usable.  We also don't make any commitment to resolving issues in these quickly.  There are still many issues with the LOAN ontologies, including LoanCore, which is the closest to being "releaseable", but all of the individuals need to be parked somewhere else in a US jurisdiction specific ontology among other issues.

Best,

Elisa
