### ISSUE TITLE
Problem with ORGANIZATION

### ISSUE THREAD

**Issue by trypuz** [edmcouncil/fibo#1845]
Resource URL:
https://spec.edmcouncil.org/fibo/ontology/FND/Organizations/Organizations/Organization

Error28:

![error28](https://user-images.githubusercontent.com/6771512/200778842-35853520-8331-46d0-869b-a744ab9c9e6b.png)

**Comment by mereolog** [comment]
@trypuz thanks for your feedback.
As of now it is a known feature due to the fact that OMG blocks its own resolution service so the OMG ontologies FIBO imports are no longer accessible. Then OWLAPI cannot recognise the ontological types of the imported resources and generates error(s) - the same issue you may find opening FIBO in Protege.
Waiting for the OMG to fix this issue we will try to handle such cases in our onto-viewer.

**Comment by ElisaKendall** [comment]
@trypuz @mereolog After working much of the afternoon off and on with Pete and Jason from OMG, I think Jason has turned off the blocking just for our ontologies. It was pretty deep in the code/settings - so he had to jump through a number of hoops. He has fixed it for Specification Metadata, and is now working on correcting it for LCC. Hopefully by tomorrow it will work as expected again.

**Comment by mereolog** [comment]
We can now import all OWL ontologies we use, so the initial problem is now solved.
The 'unexpected' behaviour of OWLAPI will be investigated in https://github.com/edmcouncil/onto-viewer/issues/299.
