### ISSUE TITLE
Use of owl:qualifiedCardinality "0"^^xsd:nonNegativeInteger

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1899]
FIBO has four instances of `owl:qualifiedCardinality "0"^^xsd:nonNegativeInteger` in OWL constraints:

1. https://spec.edmcouncil.org/fibo/ontology/DER/RateDerivatives/IRSwaps/PlainVanillaInterestRateSwap (2 instances)
2. https://spec.edmcouncil.org/fibo/ontology/IND/InterestRates/InterestRates/SpecificProviderInterestRateBenchmark
3. https://spec.edmcouncil.org/fibo/ontology/SEC/Equities/EquityInstruments/PerpetualPreferredShare

Consider this example (from SpecificProviderInterestRateBenchmark)
```
rdf:type owl:Restriction ;
owl:onProperty <https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/isProvidedBy> ;
owl:qualifiedCardinality "0"^^xsd:nonNegativeInteger ;
owl:onClass <https://spec.edmcouncil.org/fibo/ontology/BE/FunctionalEntities/Publishers/MarketDataProvider>
```
Semantically, this implies that an instance of `SpecificProviderInterestRateBenchmark` cannot have any `isProvidedBy` link to an instance of `MarketDataProvider`. This, of course, may make sense, but then why the owl:maxQualifiedCardinality is not used instead?

What convention is followed here?
Perhaps it is just a slip of pen and we should have owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger instead?
If it is, why not add a new hygiene check?

**Comment by ElisaKendall** [comment]
@mereolog In the case of a plain vanilla IR Swap, the exact qualified cardinality of 0 restriction is correct - plain vanilla IR Swaps cannot have notional step schedules. We could delete the restrictions altogether if they cause challenges, but they are correct.

The restriction on specific provider IR benchmark is in error and should be exact cardinality of 1 - nice catch.

The restriction on a perpetual preferred share is also correct though - it can't have a maturity date. So that one is also correct.

If you think I should change it from exact cardinality to max cardinality of 0 for the ones that are intentional I can make that change, though.
