### ISSUE TITLE
Possible typo "distributiojn" in SEC/Funds/CollectiveInvestmentVehicles.rdf

### ISSUE THREAD

**Issue by aamedina** [edmcouncil/fibo#1972]
https://github.com/edmcouncil/fibo/blob/2b582f02703cda759b2d6a4d8b2eb8b578fd86fb/SEC/Funds/CollectiveInvestmentVehicles.rdf#L1477C1-L1478C17

Was reviewing FIBO object properties in Protege and wanted to open an issue in case this was a typo; also in its rdfs:label. There are also a couple of variants of "has distribution policy" there which might warrant double checking in case something happened during a refactor at some point.

**Comment by ElisaKendall** [comment]
@aamedina Hi Adrian, Just wanted to let you know that I hadn't forgotten some of the other issues you raised. This ontology is still very drafty, and we haven't gotten to it yet, aside from extracting the content that is now in Funds. I'm not surprised about typos, lack of definitions in places, duplication, etc.

If you have a use case for it though, please let us know so that we can move it up in terms of priority.

Thanks!

**Comment by aamedina** [comment]
No use case, just noticed it and wanted to report it in case it wasn’t known. Want me to close? Thanks for checking in.

**Comment by ElisaKendall** [comment]
@aamedina No worries - I'll leave it open until we clean up that ontology. Just wanted you to know that I had seen it :).
