### ISSUE TITLE
Deprecated resources in use

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#2021]
There are three deprecated resources still in use:
1. https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/hasIdentity
2. https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/SecuritiesIdentificationIndividuals/ReutersInstrumentCodeScheme
3. https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/ParametricSchedules/ParametricSchedule

They were found by https://jenkins.edmcouncil.org/job/fibo/job/hygine_test_update/3

**Comment by ElisaKendall** [comment]
@merelog The use of fibo-sec-sec-idind;ReutersInstrumentCodeScheme is strictly with respect to having an owl:sameAs statement in the deprecated resource, which should be allowed for named individuals

**Comment by ElisaKendall** [comment]
@merelog The use of fibo-sec-sec-sch;ParametricSchedule is strictly with respect to having an editorial note that we have not removed, mainly due to some detail that we might want for further revisions downstream. I can remove the note, which would address the hygiene issue, but if you add something to ignore annotations on deprecated resources, then it would not show up as being still in use.

**Comment by mereolog** [comment]
This looks fine, but note that I fixed the [check for the deprecated resources](https://github.com/edmcouncil/fibo/blob/hygine_test_update/etc/testing/hygiene_parameterized/testHygiene_resources_deprecated.sparql), and now it finds quite a lot of them — see: https://jenkins.edmcouncil.org/job/fibo/view/change-requests/job/PR-2026/3/.

I looked at a couple of them, and they seem to be genuine issues, e.g., https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/ISO4217-CurrencyCodes/HRK, in the sense that they are deprecated resources that relate to other resources.
