### ISSUE TITLE
Fx: Specialize exchange rates into Buy and Sell (and Mid). 

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#46]
Applies to forward as well as spot, so should be applied to parent class (but NB change to Forward elsewhere)

**Comment by ElisaKendall** [comment]
This issue was addressed a number of years ago for spot rates, which are further subdivided into buy, mid, and sell.  Currency forward rate has not been subdivided in the same way in the ontology, however.  None of the definitions we found in IND fct discussions broke forward exchange rates down in this manner, because they occur sometime in the future; buy, mid, and sell rates are typically for a specific day or window that is near term / current.

I recommend that we close this, since the work was done for spot rates.  If a future use case identifies the need for the same divisions for forward rates, we can reopen it or create a new issue at that time.
