### ISSUE TITLE
Fx: Reference method of calculation for Fx Spot rate

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#50]
Introduce “Method” and use it here (as well as for unemployment rates etc. as noted previously).

Also make it clear this is not the rate for a given transaction but a market quote

**Comment by ElisaKendall** [comment]
Currency Spot Rate is now a subclass of quoted exchange rate, and we have added other properties related to quoted rates as well, such as the quotation date.  I'm not certain why this was reopened given that the hierarchy has changed so much as have the definitions since this was raised as an issue.  

I'm closing this.  If there is a new issue related to currency spot rates then raise that against the current ontology in JIRA.
