### ISSUE TITLE
Domain and Range of hasPercentageValue and hasNumericValue

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#72]
Why is domain of hasNumericValue Thing? How can a LegalEntity have a percentageValue? 

Proposed change: 
Introduce this property to the most abstract class for which it might be meaningful. This would now exist, in the extended Analytics ontology.

**Comment by ElisaKendall** [comment]
Commenting because Pete reopened this issue.  The property hasPercentageValue no longer exists, so the issue related to that property has been made moot. 

Many things can take numeric values, such as a QuantityValue (in the QuantitiesAndUnits ontology), and hasNumericValue is the superproperty of many others - hasAmount, hasRateValue, hasWeight,  hasDefaultLotSize, hasPoolNumber ... and there are other properties that likely -should- be subproperites of this property.  Of the classes in Production that use this property, some of them are subclasses of QuantityValue already, but others are not, because we use hasAmount for things like numbers of shares (issued, outstanding, treasury), where that usage is not in the context of something that is a quantity value, although it -is- in the context of something that has some amount associated with it.

I propose we close this.
