### ISSUE TITLE
import problem in EquityPricing.rdf

### ISSUE THREAD

**Issue by trypuz** [edmcouncil/fibo#850]
See line 64 in [EquityPricing.rdf](https://github.com/edmcouncil/fibo/blame/master/MD/EquityTemporal/EquityPricing.rdf)

**Comment by rivettp** [comment]
Would be useful to quote the line, since other changes might cause the line number to change. It's 		`<owl:imports rdf:resource="https://spec.edmcouncil.org/fibo/ontology/FND/ClassificationSchemes/"/>`
and should have the Arrangements module:

`<owl:imports rdf:resource="https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/ClassificationSchemes/"/>`
