### ISSUE TITLE
Invalid values for xsd:dateTime datatype

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#855]
Running Hermit reasoner (version 1.4.3.456) over Production version of Fibo from 2019Q4,1 spawned the following error:

_ERROR  08:47:38  An error occurred during reasoning: Literal "2012-06-26T13:54:19.798000"^^<http://www.w3.org/2001/XMLSchema#dateTime> is malformed.
org.semanticweb.HermiT.datatypes.MalformedLiteralException: Literal "2012-06-26T13:54:19.798000"^^<http://www.w3.org/2001/XMLSchema#dateTime> is malformed
at org.semanticweb.HermiT.datatypes.datetime.DateTimeDatatypeHandler.parseLiteral(DateTimeDatatypeHandler.java:66) ~[na:na]_
....

It seems to me that the reason for this error are the trailing zeros in '2012-06-26T13:54:19.798**000**' literal.

The W3C recommendation specifies the following constraint on the values of xsd;dateTime datatype (https://www.w3.org/TR/xmlschema-2/#dateTime):

_Except for trailing fractional zero digits in the seconds representation, '24:00:00' time representations, and timezone (for timezoned values), the mapping from literals to values is one-to-one. Where there is more than one possible representation, the canonical representation is as follows:

The 2-digit numeral representing the hour must not be '24';
The fractional second string, if present, must not end in '0';_

So this particular value should be '2012-06-26T13:54:19.798' instead.

Note that Fibo has 66 such instances - their list is attached below:
[fibo_invalid_datatime_values.xlsx](https://github.com/edmcouncil/fibo/files/4154092/fibo_invalid_datatime_values.xlsx)

I think a similar issue was raised in https://github.com/edmcouncil/fibo/issues/85, but no resolution seems to have been provided.

**Comment by ElisaKendall** [comment]
These original time stamps were extracted verbatim from the ISO GLEIF repository.  We did not feel that we could change them due to their occurrence in reference data, which is what we are publishing them to emulate.  

Having said this, a recent change to the GLEIF data, currently in beta, is correcting this.  We are working on a resolution to a securities issue that will fix this using the latest GLEIF information.

That work is in progress, is tedious, and the dates and times are not the same as those in the prior examples, so please leave this to the securities working group.  We will consider doing a partial update to fix it while our remaining work is in flight, but hopefully it will be corrected within a week or two.  I'm waiting on feedback from other SEC members before doing the pull request that will include fixes for at least a number of these individuals, and then a subsequent fix will correct the remainder of them.

**Comment by rivettp** [comment]
I believe these are now all fixed, from a visual inspection.
