### ISSUE TITLE
Tabular summary of Ontologies

### ISSUE THREAD

**Issue by dallemang** [edmcouncil/fibo#857]
The former FIBOPedia had as a by-product an Excel summary of the ontologies.  This was in response to a specific request by FIBO users.  The new Fibo Viewer subsumes most capabilities of the FIBO Pedia, but not this one.  it is easy enough to produce this as a stand-alone product.  We should do so, give it a name, and offer it on the website.

**Comment by trypuz** [comment]
@dallemang, what did the Excel summary of the ontologies contain?

**Comment by rivettp** [comment]
The table is already being produced - see for yourself at https://spec.edmcouncil.org/fibo/fibopedia/master/latest/FIBOpedia.xlsx .
(for some reason this does not work for me in Chrome though https://spec.edmcouncil.org/fibo/fibopedia/master/latest/FIBOpedia.csv 
does)

**Comment by trypuz** [comment]
Thank you @rivettp. BTW, this or next week FIBO Viewer will have a new feature that will even better indicate the maturity level of each ontology, module, domain, and even resource. Do we really need a tabular summary of FIBO ontologies? IMO we should better focus on improving [FIBO Viewer](https://spec.edmcouncil.org/fibo/ontology).

**Comment by rivettp** [comment]
We're already producing the table, it just needs a link from the website. 
It was specifically requested by several people in the EDMC community as a concise downloadable summary, even when we had the online interactive version.

**Comment by VladimirAlexiev** [comment]
@rivettp the links you gave Feb 5 don't work and in fact I can't find FIBOpedia.csv anywhere on the web, and only a few matches for "FIBOpedia" in this github repo.

**Comment by rivettp** [comment]
Since I wrote that message, the FIBOpedia step was removed from the build process - which I objected to as part of the PR #854 review since it did no harm and it's relied by my own (Adaptive) software. But I was overridden by @trypuz which explains why the CSV file is no longer there: he wanted to remove it and consider reinstating it via this issue. However this issue is still sitting here 2 months later and my software is still unable to access the latest module structure which it expects to load from the FIBOpedia output.
The script is in the ontology-publisher GitHub repository under publisher/product/fibopedia
