### ISSUE TITLE
fibo-sec-sec-iss:SecuritiesOffering in SEC and BP

### ISSUE THREAD

**Issue by trypuz** [edmcouncil/fibo#865]
[fibo-sec-sec-iss:SecuritiesOffering](https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/SecuritiesIssuance/SecuritiesOffering) is defined both in [SecuritiesIssuance.rdf](https://github.com/edmcouncil/fibo/blob/master/SEC/Securities/SecuritiesIssuance.rdf) and [IssuanceProcessTerms.rdf](https://github.com/edmcouncil/fibo/blob/master/BP/SecuritiesIssuance/IssuanceProcessTerms.rdf) with different restrictions and annotations. The SEC  specification seems to be the correct one.

**Comment by rivettp** [comment]
There is nothing wrong with one ontology adding further restrictions on a concept defined in another, since the concepts needed might well not be available in the original or its set of imported ontologies (bearing in mind our rule to avoid import cycles)
That is the case here.
However what are wrong are some of the annotation properties such as the label and definition in IssuanceProcessTerms.

**Comment by ElisaKendall** [comment]
Issuance Process Terms has lots of challenges - this is a very provisional ontology that has not been reviewed.  I'll take a crack at it to eliminate some of the duplication, though, including this class.
