### ISSUE TITLE
Property hasSharesOutstanding should be applied to the Entity

### ISSUE THREAD

**Issue by rivettp** [edmcouncil/fibo#870]
Either way, SEC examples should have values for this: it's important to be able to check the ontology works, and to provide the basis for other measures such as market cap and Earnings Per Share (even if we cannot get an accurate value).
Personally I think [the property](https://spec.edmcouncil.org/fibo/ontology/SEC/Equities/EquityInstruments/hasSharesOutstanding) should be applied to the Entity rather than the Share individual since the latter may not work if there are multiple classes of share with different voting rights.

_Originally posted by @rivettp in https://github.com/edmcouncil/fibo/diffs_

**Comment by ElisaKendall** [comment]
This is a bit more complicated that the issue implies.  A share, as defined in the equities ontology, is (1) a financial instrument that signifies a unit of equity ownership in a corporation, or (2) a unit of ownership in a mutual fund, or (3) interest in a general or limited partnership, or (4) a unit of ownership in a structured product, such as a real estate investment trust.  So we can't simply put the properties related to issued shares, shares outstanding, treasury shares, etc. on Corporation.  We could create the concept of an equity issuer, whose subclasses are corporation as issuer, partnership as issuer, mutual fund issuer, and structured product issuer, and add the properties to that class, if that's what you think should happen here, but it can't just be on a corporation in its issuer role, and yet it doesn't make sense on all issuers, since there are some that are not issuers of shares.

**Comment by ElisaKendall** [comment]
One option would be to remove the domain, but leave the properties there, and then they can be used appropriately - is that sufficient?

**Comment by ElisaKendall** [comment]
That approach would correspond to the approach I took with the individuals, for AlphabetIssuer, for example.
