### ISSUE TITLE
Problems with Q1 2020 Release Notes

### ISSUE THREAD

**Issue by rivettp** [edmcouncil/fibo#964]
There are many issues, some technical, but many related to what it makes sense to have in Release Notes - things that would be useful to FIBO release consumers and that describe changes in appropriate detail to have meaning. 

As part of the Release Notes we should list those ontologies added (to Production) and deleted in the quarter. As well as a total count of those in Production and Development.

Overall we need to ensure (and include in our review) that each PR has a comment suitable for inclusion in release notes. That summarizes all the changes (maybe add that to the PR checklist). We should NOT use Commit messages which a) are not intended for that purpose and b) often represent the individual developer's way of working rather than substantive changes.

Some of them are so minor as to be not worth mentioning, and when they are mentioned they have so little detail they are useless e.g. "added missing definition" is useless without saying what concept it was added to. There is so much clutter that it's hard to see what might gave changed of interest. Some of the detail relates purely to the internal PR review or hygiene process and not to any visible change at the end of it

The first line says the 'activities were use case driven" but it does not say which use cases drove which changes.
References to "informative" and "provisional" should not be in these release notes - FIBO presents releases as either Development or Production.

The reference numbers e.g. FBC-245 and GitHub issue numbers should be explained in an introduction. Also a warning that many people may not be able to access GitHub issues.

Generally the domain and concept names should start with capital letters whenever mentioned e.g. "The focus in Derivatives".
Overall there is inconsistency as to whether concepts are referenced in all lower case or camelCase.

Again, generally, I think it's ridiculous to have many bullets all with identical issue numbers e.g. there are 13 separate lines all starting "FBC-245". 

For BP the detailed changes all reference the same Issue - which looks odd and a possible copy and paste error. Better if anything to have a few sentences nested under a single issue bullet. The actual changes do not seem directly related to #865 so maybe it is a copy and paste error.

For DER the detailed changes bear no resemblance to the Highlights: surely the latter should summarize/pick out detail from the former!

For FBC the 2 bullets for FBC-238 could easily be combined.

For LOANS, the text still gives the reader no idea what "coagulate" means in this context. I was around at the time and I don't remember even! 
Worse it gives the impression that LOANS continues to be actively worked on, which it is not: if people want it they need to fund it!

MD-850 why even mention this since the whole ontology was eliminated so no one will ever see the change in a release! 

Typos:
line 2 "companies the issue shares" -> "companies that issue shares"
FBC line 1 "were driving by use case" -> "were driven by use case"
IND-77 one of the many lines has an odd line break between "to an" and "explanatory note"
LOAN-146 odd linebreak between "circular" and "imports"

**Comment by dallemang** [comment]
I see two approaches to this - one is to modify the process by which we record changes, so that the release notes that are created this way will be more readable.  The other is to simply spend the time editing the 2020Q1 release notes to make them more readable. 

The first time we did this, I did some editing on the log, but not very much.  I really didn't expect the  verbatim log to be very interesting to anyone (for all the reasons @rivettp  outlines above, and more).  Neverthess, when I released the first one, @DennisWisnosky informed me that these notes were very popular - I'm not sure who they were popular with; we didn't have that big an audience in those days.  

This is why I ask Elisa to write a custom summary for each section; I consider these to be the real release notes, and the git log, is really an _aide memoire_ for @ElisaKendall to help her write them. Exposing these is sort of like 'showing your work' in a maths exam; you don't just give the answer, you show all the steps.  That would suggest that I just include the git log verbatim, but it is even worse than what you are seeing here (in terms of repetition, incomplete sentences, ellipses, etc.). 

We can spend more time editing these things, or maybe we should leave them out entirely.

**Comment by ElisaKendall** [comment]
In a software / systems development organization, a technical writer would take the raw content, ask questions of the developers, and produce proper documentation.  But that isn't the case here.   Instead, we're doing exactly what Dean outlined - I attempt a summary, at the top of each domain level, and maybe fix spelling here and there, merge a few duplicate lines, make sure the issue that was fixed is included and that's it.  We really don't have the resources to do more than that.

**Comment by rivettp** [comment]
Firstly, I think it's worth giving this some attention. Unless our efforts are purely for ourselves, what's the point if people don't know what we've done? Especially those who might have spurned FIBO in the past as not being up to their needs.

However I'm not suggesting a lot of effort: to me what we have with the Highlights is sufficient and I would remove the commit comments from these Release Notes, which in 90% of cases add no value.
Going forward we should introduce the discipline I proposed for the PR comments, which should also make the Commit comments unnecessary.

I also made some high-level comments we should act on for this Release:
 - reference the specific use cases which drove specific areas of change mentioned in the Highlights (IOW don't just say "use case driven")
 - replace "coagulate" by an explanation someone could understand
 - provide the totals: ontologies added and removed this quarter (by PRod and Dev), and new totals

Something I just realized we're not clear on is that the Release Notes cover not only Release/Production ontologies (which are in theory the focus of the quarterly release) but also Development ontologies (like Loans). In fact, stepping back, our whole messaging on Production is confused now we no longer publish the Primer. Best I could find was here https://spec.edmcouncil.org/fibo/OWL which is in the wrong place (Production applies to all the products) and does not explain that Production ontologies continue to evolve during the quarter and can be downloaded along with the Development ontologies.

Finally it would be nice if we could provide an overview of what we think FIBO now adequately covers for Production purposes. Not sure how best to do this, but for example we spent effort (previous quarter) getting Bonds into pretty good shape. How would someone coming anew to FIBO know that (without trawling through all the release notes and noticing a line from Q4 2019).
A start might be something like what we had with FBOpedia module table which showed the abstract and status of all modules without needing to open up the tree structure one branch at a time.

**Comment by bobbinteegarden** [comment]
Great summary, Pete.  Could we add graphs, bar charts, visualizations that show what content, what level of completion, where all the modules are, in all categories:  Prod, Dev, and even considered (to get some feedback on interest)?
 
 
Bobbin Teegarden
CTO/Chief Architect, OntoAge
 <mailto:bobbin@ontoage.com> bobbin@ontoage.com
206.979.0196 cell
425.378.0131 home/fax
Bellevue, WA

**Comment by dallemang** [comment]
I have to say, the first time I assembled these, I was surprised that anyone would find the detailed change notes useful.  I had at the time hearsay evidence that they did, but I can't document that. 

I would be quite happy just using these as the starting point for @ElisaKendall  (and others) to write the summary. 

I really like the idea of stats; I think that those will probably be more informative than anything else.  We can even do them retroactively. 

e.g., numbers of ontologies / classes / properties in production / dev  for each module.   This would show the progress we (mostly Elisa) are making in a visual way.

**Comment by ElisaKendall** [comment]
One thing that would help is that when the merges are done in github, can we compress all of the commits?  I typically don't do that myself, but was under the impression that it could be done.  I would prefer not to write lengthy notes about every minor thing that I change, such as fixing a URI in the process of working on a given issue resolution.  I also tend to commit changes relatively often when working on a big change so that (1) I don't risk losing work, and (2) anyone that is reviewing what I've pushed out can see where things stand and provide feedback before I call something done.  I often do that for use-case specific changes, when I'm sharing the work with folks on our FCT calls, so that they can load it for themselves even in an interim state.  Most of our current group members don't do this, but they could.  That means that there are a number of interim commits which may not be of interest to most casual observers, and definitely not to folks who download FIBO on a quarterly basis and only want the top line details.

**Comment by rivettp** [comment]
Yes, @ElisaKendall, squashing of commits can be done on merging a PR, and it's something I thought we'd agreed to do. Indeed a repo can be configured to require it https://help.github.com/en/github/administering-a-repository/configuring-commit-squashing-for-pull-requests

**Comment by rivettp** [comment]
It's one of the (many) things I said should be added to contributing.md in #862 (4 bullets from end).
