### ISSUE TITLE
Incorrect definition of Organization

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#97]
The definition given in FND/ORG/ORG for Organization is: 

"A social unit of people, systematically structured and managed to meet a need or pursue collective goals on a continuing basis."
Source is given as: http://www.BusinessDic-tionary.com/

This is incorrect: the intended scope for organization, and the properties modeled for it, are that an organization may have members which are any kind of autonomous agent. The definition limits membership of an organization to "people", which on any interpretation means human beings alone. 

Proposed resolution: 
Change definition to: 
"An organization consists of one, two or more individuals participating in an entity which is an autonomous thing, usually set up for some purpose. "
Change definitionOrigin to: EDM Council

Note: I was going to propose the W3C Organization class definition, but this also has "people". This may have (separate) implications for alignment with the W3C Organization ontology.

**Comment by rivettp** [comment]
Reopening this since the current definition, though quite different, is still specific to persons:
"a unique framework of authority within which a person or persons act, or are designated to act, towards some purpose, such as to meet a need or pursue collective goals on a continuing basis"

The new definition additionally seems over-restrictive and does not encompass an InformalOrganization which is a subclass.

**Comment by ElisaKendall** [comment]
This definition was taken from the ISO 6523 standard, which could indeed include informal organization.  

Every organization that we have needed to address based on FIBO use cases must have at least one person as its documented head, at a minimum on paper, including trusts, funds, and all other organizations that we care about.  We have no use cases for informal organizations that are not incorporated, even a community soccer team needs to have incorporated as some kind of benefit corporation in order to open a bank account in the US or EU.  If you have a use case for an organization that is not banked and is more informal than a PTA or soccer team, then post it.  Otherwise, using the ISO definition of organization is at least unimpeachable from a source perspective.

I propose that we close this because the notion of an informal organization is not needed for any use case we have at present.

**Comment by rivettp** [comment]
In that case we should deprecate InformalOrganization because currently we're asserting that it complies with that pretty heavyweight definition.

**Comment by MikeHypercube** [comment]
Indeed. The original use case, established during SME reviews, was the need to talk about cartels and other informal groupings, including those that are organizations as well as those that are not. 

Separately, it should be clear that the meaning of a concept does not change according to the scope of ways we happen to know it might be used. Either we define 'organization' as what it actually is (leaving out those sub classes we don't think we need), or we define something that corresponds to Elisa's narrower scope, but then it is not 'organization' as the concept is most broadly defined.
