### ISSUE TITLE
Suggestions for ONTOLOGY_GUIDE

### ISSUE THREAD

**Issue by VladimirAlexiev** [edmcouncil/fibo#983]
Suggestions for https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md
1. fix the bolding. There must be no spaces between the bolded phrase and `**`. Because of such problems some bolding seems almost random. Particularly this section https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions and next
1. give example of "genus / differentia" definition
1. give prefixed URLs of props in https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#additional-annotations
1. "property naming .. without the inclusion of the name of the domain or range class names": I completely agree re domain (maybe not so much re range). You could give some counter-example, eg https://schema.org/legislationDateVersion, which would be more universal if it was named and defined as `versionDate` (https://github.com/schemaorg/schemaorg/issues/1736)
1. break up this big section https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#overarching-principles and give some examples
1. eg for "we attempt to define properties at the highest level in the property hierarchy", a number of counter-examples can be found in schema.org: 
    - https://github.com/schemaorg/schemaorg/issues/1736 where the lifesci extension has misappropriated common words like `action, warning, procedure, status`
    - https://github.com/schemaorg/schemaorg/issues/1513 where Abdomen really means "a PhysicalExam of the Abdomen"
1. "why we don't reuse the OWL Time ontology from the W3C, and why we don't use the PROV-O ontology for provenance": please also comment about the use of XSD types
1. "increasingly limiting the number of philosophically-grounded concepts at our highest levels": I am glad, over-abstraction is an enemy. Please make some examples where this is not yet done, and describe these harder to understand patterns. In particular `comprises`, a financial noob like me balks at things like `SecuritiesIssuanceSPV fibo-fnd-rel-rel:comprises owl:someValuesFrom  SecuritizedDebtPool`
1. https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t2-synonyms-as-classes "equivalences relate two named classes ... only those that are identified that do not violate this policy should be allowable": it seems to me the policy forbids equivalent classes (and I completely agree, this follows form Occam's razor), so how can an equivalent class not violate it?
1. "RDARR compliance": what's that?
1. https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t2-synonyms-as-classes: clarify why `synonym` should be used and not `altLabel`: https://github.com/edmcouncil/fibo/issues/980
1. "cycles among ontologies" -> "cycles among classes"
1. "Resource" for data properties": don't you mean "Literal"?
1. "relation is very general and the range should be the most general concept “Thing”": I thought I saw elsewhere that you frown at owl:Thing (and indeed, it's used very sparingly in latest releases)
1. https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t12-missing-inverse-relationships: FIBO Has 1465 ObjectProperty but only 99 inverses, so please clarify this policy or make a statement when do you hope to achieve it? 
1. BTW I side with PROV designers that inverses are not needed, because you can always query in the opposite direction. The Ontotext Platform has `inverseAlias` to allow such navigation in GraphQL

**Comment by ElisaKendall** [comment]
Thanks!  I agree with most of your comments, aside from the comment about inverses - in case an application chooses to assert the inferences for performance reasons (we do that at a couple of my clients, in fact).  I'll definitely work responses to some of these in as time permits.  

Quick answer to your question about OWL Time and Prov-O -- the last time I downloaded either ontology they included bugs or were logically inconsistent.  I've asked developers of each about plans to correct that, and there are none to my knowledge.  That may have changed recently, and it would be good to recheck before I say anything about that in the guide, but that was the case as we were deciding how to represent dates and times, for example, which uses datatypes that are not allowed in OWL among other issues.  And for FIBO, the ability to represent complex schedules is very important, which OWL Time does not support.

**Comment by VladimirAlexiev** [comment]
(Below I use numbers to refer to the list above. I use a paren instead of dot, so the Markdown renderer doesn't rewrite my number to sequential)

7) I have no beef about OWL Time and PROV-O.
I asked about XSD datatypes. You already explained to me why xsd:dateTime is not suitable (because no total order), please explain it in the guide. 
I think FIBO now uses XSD whenever possible? I saw FND/Utilities/Values/IntegerValue but with guideline "Note that this class is not intended to be used directly (in these cases use xsd:integer) but is intended to be subclassed with values with business semantic intent"

16) "application chooses to assert the inferences for performance reasons": PROV handles this with `prov:inverse`: declaring what name should be used for the inverse, but not triggering inverse inference: https://www.w3.org/TR/prov-o/#inverse-names

**Comment by VladimirAlexiev** [comment]
17: (new one, related to #979). Please explain why you use owl:DatatypeProperties with `^^xsd:anyURI` instead of owl:ObjectProperties without range.

**Comment by VladimirAlexiev** [comment]
18: in particular, I think it's bad style to represent the same resource as anyURI literal and as IRI so I'd suggest you change this particular use. This IRI is in fact an object: a `owl:Ontology`, see #992

```ttl
	sm:dependsOn
"https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/CurrencyAmount/"^^xsd:anyURI ,
	owl:imports
<https://spec.edmcouncil.org/fibo/ontology/master/latest/FND/Accounting/CurrencyAmount/> ,
```

**Comment by VladimirAlexiev** [comment]
19: State that no ontology uses relative URLs and empty prefix, which are bad practices. #996

**Comment by trypuz** [comment]
@VladimirAlexiev, thank you for your comments. I'll take care of this issue.

**Comment by ElisaKendall** [comment]
A fewf comments, @trypuz, and perhaps we should collaborate on any revision:
7.  xsd:dateTime is ok and we do use it, but not xsd:date or xsd:time because they are ambiguous and disallowed per the OWL 2 specification.  The set of XSD datatypes we use are strictly those that the OWL 2 specification allows, and of those, we typically use a subset, e.g., xsd:token, etc.

11. Use of a synonym annotation as opposed to altLabel - this was a policy decision made several years ago, as we felt that altLabel was not sufficiently explicit as to when the lable should be used.  We included synonym and abbreviation as FIBO annotations to help clarify the meaning of the alternative label, so, for example, an abbreviation should not be considered a synonym, it should be properly identified as an abbreviation.  We also decided that use of abbreviations in class names should be minimized if not eliminated.  There are still cases in provisional where you see these, but as the ontologies are promoted to release, most, if not all, of those cases will be eliminated.

12. We elected to disallow cycles among ontologies as well as among classes - if you are using an ontology as the basis for generating software, which, for example, JPMC was considering or does, then you can't have cycles at all.  There are still some in provisional that need to be rectified, but none in the released ontologies.

14.  The only case where owl:Thing is allowed in FIBO is as the target of a someValues restriction, when you need to say that something is required as a constraint on some class that has a particular property, but we did not want to incorporate a giant union, or when we were too high up in the hierarchy to specify, such as in some cases in Foundations.

15.  Not all properties need an inverse, such as some of those that indicate x is a characteristic of y, although we have attempted to establish inverses when it is important to do so.  There are a number of users of FIBO that do want the inverse reasoning, and that for performance reasons tend to assert all inferences (not just inverses) out of band and use them in their knowledge graphs operationally.  But, we have been erring on the side of conservatively establishing inverses when it is clear that they are important, rather than in every case.  The number of object properties in development is likely to drop substantially as we revise those ontologies and integrate them with release, so I would not depend on most of them - there are roughly 535 object properties in production (which should be reviewed to see if we really need them all and to reduce that number substantially if we can generalize/reuse), and over 1400 as you mention in development.  Many of the ones in dev are duplicates and will go away.  Then of the remainder, some additional analysis is still needed to see which really need to have inverses, and for us to add those as we encounter them via use cases and testing.  But, the difference between the number in development and the ~80 that have inverses in the released ontologies is probably not a good comparison.

18.  If you use OWL reasoning, there are certain declarations / uses that disallow a URI in the range.  So for annotations we've used anyURI.  There may be some inconsistencies due to historical development with respect to other things - for data properties we are attempting to use the resource where possible, but we may not have addressed nearly all of them, as this has been a lower priority to other bug fixes.  The main thing is that whatever we do has to be logically consistent at the end of the day, and the reasoners complain if you declare a property one way and use it in another.

**Comment by rivettp** [comment]
On 12 @ElisaKendall you wrote "- if you are using an ontology as the basis for generating software, which, for example, JPMC was considering or does, then you can't have cycles at all." I'd strongly challenge this, unless the generator was using a very naive algorithm. Furthermore most languages that you might generate, including Java and XSD, also allow import cycles.

On 12 you wrote "for data properties we are attempting to use the resource where possible, " - I assume you mean "object properties" since by definition datatype properties cannot have a resource as the object of their triples?

**Comment by rivettp** [comment]
@trypuz if you are updating the Guide I'll email you a bunch of comments/suggestions I made which were in the form of markup.

**Comment by ElisaKendall** [comment]
@rivettp - imports cycles perhaps, although we've attempted to eliminate them because tools like No Magic's MagicDraw at least used to have issues with imports cycles (not sure about the latest version), but cycles among classes can lead to infinite loops in code and are challenging for reasoning purposes.
and yes on 12 - sorry, was typing faster than brain cells were firing.

**Comment by VladimirAlexiev** [comment]
hi @rivettp where is your bunch of comments/suggestions and does the commit above address them?
I think EDM's ontological approach in FIBO is very good so it'll pay to make the GUIDE maximally clear and detailed, so other communities can benefit from this approach.
